
-- This syntax will create the new DB

  CREATE DATABASE IF NOT EXISTS GRATLYDB;


-- This table is the first table created after customer is onboarded

  CREATE TABLE IF NOT EXISTS GRATLYDB.SRC_ONBOARDING (
         RESTAURANTID INT AUTO_INCREMENT PRIMARY KEY,
         RESTAURANTGUID VARCHAR(36) NOT NULL,
         PAYOUT_FEE_PAYER VARCHAR(32),
         PAYOUT_FEE VARCHAR(32),
         ACTIVATION_DATE DATE,
         FREE_PERIOD VARCHAR(32),
         BILLING_DATE DATE,
         BILLING_AMOUNT VARCHAR(32),
         ADMIN_NAME VARCHAR(128),
         ADMIN_PHONE VARCHAR(32),
         ADMIN_EMAIL VARCHAR(128)
     );

ALTER TABLE GRATLYDB.SRC_ONBOARDING AUTO_INCREMENT = 100;

-- INSERT INTO GRATLYDB.SRC_ONBOARDING(RESTAURANTGUID ,SECRETKEY, CLIENTSECRET, USERACCESSTYPE) values('0169bd32-becf-4b04-9093-d7d4db1dc242','WZ8mobWCpK4AcXQjDHgZcgQIMOCaQ3xs','XsplfAXitqH1ePen0nkEWV_lFuCEaabjEPhpagi_zLlKxDVdIrPdwhWJgj0W2o2v','TOAST_MACHINE_CLIENT');

-- This script will store the details of the restaurant(s) and is a source table

  CREATE TABLE IF NOT EXISTS GRATLYDB.SRC_RESTAURANTDETAILS(
        RESTAURANTGUID VARCHAR(36) PRIMARY KEY,
        RESTAURANTNAME VARCHAR(128) NOT NULL,
        LOCATIONNAME VARCHAR(128),
        LOCATIONCODE VARCHAR(64),
        DESCRIPTION VARCHAR(128),
        TIMEZONE VARCHAR(128),
        CURRENCYCODE VARCHAR(32),
        FIRSTBUSINESSDATE VARCHAR(16),
        ARCHIVED VARCHAR(8),
        ADDRESS1 VARCHAR(256),
        ADDRESS2 VARCHAR(256),
        CITY VARCHAR(32),
        STATECODE VARCHAR(16),
        ZIPCODE VARCHAR(8),
        COUNTRY VARCHAR(32),
        PHONE VARCHAR(16),
        WEBSITE VARCHAR(512),
        ORDERONLINE VARCHAR(512)
  );

-- This script will store the details of all employees for all restaurants and is a source table

  CREATE TABLE IF NOT EXISTS GRATLYDB.SRC_EMPLOYEES (
        RESTAURANTGUID VARCHAR(36) ,
        EMPLOYEEGUID VARCHAR(36) NOT NULL UNIQUE,
        EMPLOYEEFNAME VARCHAR(64),
        EMPLOYEELNAME VARCHAR(64),
        CHOSENNAME VARCHAR(64),
        PHONENUMBER VARCHAR(16),
        EMAIL VARCHAR(64),
        DELETED VARCHAR(8),
        DELETEDDATE DATE,
        PRIMARY KEY (RESTAURANTGUID, EMPLOYEEGUID),
        CONSTRAINT FK_RESGUIDEMP FOREIGN KEY(RESTAURANTGUID) REFERENCES  
        GRATLYDB.SRC_RESTAURANTDETAILS(RESTAURANTGUID)

  );
-- This table stores all different type of jobs for all the restaurants and is a source table

  CREATE TABLE IF NOT EXISTS GRATLYDB.SRC_JOBS (
        RESTAURANTGUID VARCHAR(36),
        JOBGUID VARCHAR(36) NOT NULL UNIQUE,
        JOBTITLE VARCHAR(64),
        ENTITYTYPE VARCHAR(32),
        CREATEDDATE DATE,
        DELETED VARCHAR(8),
        DELETEDDATE DATE,
        CODE VARCHAR(36),
        TIPPED VARCHAR(8),
        DEFAULTWAGE VARCHAR(32),
        WAGEFREQUENCY VARCHAR(32),
        PRIMARY KEY (RESTAURANTGUID,JOBGUID),
        CONSTRAINT FK_RESGUIDJOB FOREIGN KEY(RESTAURANTGUID) REFERENCES  
        GRATLYDB.SRC_RESTAURANTDETAILS(RESTAURANTGUID)
  );


-- This table stores all roles assigned to an employee by the Restaurant and is a source table

  CREATE TABLE IF NOT EXISTS GRATLYDB.SRC_EMPLOYEEROLE (
        RESTAURANTGUID VARCHAR(36),
        EMPLOYEEGUID VARCHAR(36),
        NAME VARCHAR(64),
        JOBGUID varchar(36),
        PRIMARY KEY(RESTAURANTGUID,EMPLOYEEGUID,JOBGUID),
        CONSTRAINT FK_RESGUIDEMPR FOREIGN KEY(RESTAURANTGUID) REFERENCES  
        GRATLYDB.SRC_RESTAURANTDETAILS(RESTAURANTGUID),
        CONSTRAINT FK_EMPGUID FOREIGN KEY(EMPLOYEEGUID) REFERENCES  
        GRATLYDB.SRC_EMPLOYEES(EMPLOYEEGUID),
        CONSTRAINT FK_JOBGUID FOREIGN KEY(JOBGUID) REFERENCES  
        GRATLYDB.SRC_JOBS(JOBGUID)
  );

-- This script stores all tables in the restaurant and is a source table

  CREATE TABLE IF NOT EXISTS GRATLYDB.SRC_TABLES (
     RESTAURANTGUID VARCHAR(36),		
     TABLEGUID VARCHAR(36),
     ENTITYTYPE VARCHAR(16),
     TABLENAME VARCHAR(32),
     PRIMARY KEY(RESTAURANTGUID,TABLEGUID),
     CONSTRAINT FK_RESGUIDTAB FOREIGN KEY(RESTAURANTGUID) REFERENCES  
     GRATLYDB.SRC_RESTAURANTDETAILS(RESTAURANTGUID)
  );

-- This table get all time entries for all employees for the current day and is a source table

  CREATE TABLE IF NOT EXISTS GRATLYDB.SRC_TIMEENTRIES (
    RESTAURANTGUID VARCHAR(36),		
    TIMEENTRYGUID VARCHAR(36),
    ENTITYTYPE VARCHAR(50) NOT NULL,
    EXTERNALID VARCHAR(255),
    EMPLOYEEGUID VARCHAR(36),
    JOBID VARCHAR(36),
    SHIFTREFERENCE VARCHAR(36),
    INDATE VARCHAR(36),
    OUTDATE VARCHAR(36),
    BUSINESSDATE VARCHAR(12),
    REGULARHOURS DECIMAL(5,2) DEFAULT 0.00,
    OVERTIMEHOURS DECIMAL(5,2) DEFAULT 0.00,
    HOURLYWAGE DECIMAL(7,2),
    TIPSWITHHELD DECIMAL(7,2) DEFAULT 0.00,
    NONCASHSALES DECIMAL(10,2) DEFAULT 0.00,
    CASHSALES DECIMAL(10,2) DEFAULT 0.00,
    NONCASHGRATUITYSERVICECHARGES DECIMAL(10,2) DEFAULT 0.00,
    CASHGRATUITYSERVICECHARGES DECIMAL(10,2) DEFAULT 0.00,
    NONCASHTIPS DECIMAL(5,2),
    DECLAREDCASHTIPS DECIMAL(10,2),
    AUTOCLOCKEDOUT BOOLEAN DEFAULT FALSE,
    DELETED BOOLEAN DEFAULT FALSE,
    CREATEDDATE VARCHAR(36),
    MODIFIEDDATE VARCHAR(36),
    DELETEDDATE VARCHAR(36),
    PRIMARY KEY (RESTAURANTGUID,TIMEENTRYGUID),
    CONSTRAINT FK_RESGUIDTME FOREIGN KEY(RESTAURANTGUID) REFERENCES  
    GRATLYDB.SRC_RESTAURANTDETAILS(RESTAURANTGUID),
    CONSTRAINT FK_EMPGUIDTME FOREIGN KEY(EMPLOYEEGUID) REFERENCES  
    GRATLYDB.SRC_EMPLOYEES(EMPLOYEEGUID)
  );

-- This table contains all orders for current day for all restaurants and is a source table

  CREATE TABLE IF NOT EXISTS GRATLYDB.SRC_ALLORDERS (
    RESTAURANTGUID VARCHAR(36),
    ORDERGUID VARCHAR(36),
    DISPLAYNUMBER INT,
    BUSINESSDATE VARCHAR(12),
    ORDERSOURCE VARCHAR(64),
    TABLEGUID VARCHAR(36),
    ORDERPAIDDATE VARCHAR(36),
    VOIDED VARCHAR(8),
    OPENEDDATE VARCHAR(36),
    PREPTIME VARCHAR(32),
    PAYMENTTYPE VARCHAR(16),
    REFUNDSTATUS VARCHAR(16),
    PAYMENTSTATUS VARCHAR(16),
    NETAMOUNT DECIMAL(7,2),
    TIPAMOUNT DECIMAL(5,2),
    GRATUITYAMOUNT DECIMAL(5,2),
    TAXAMOUNT DECIMAL(7,2),
    TOTALAMOUNT DECIMAL(7,2),
    EMPLOYEEGUID VARCHAR(36),
    NUMBEROFGUESTS INT,
    DURATION BIGINT,
    APPROVALSTATUS VARCHAR(16),
    PRIMARY KEY (RESTAURANTGUID,ORDERGUID),
    CONSTRAINT FK_RESGUIDALO FOREIGN KEY(RESTAURANTGUID) REFERENCES  
    GRATLYDB.SRC_RESTAURANTDETAILS(RESTAURANTGUID),
    CONSTRAINT FK_EMPGUIDALO FOREIGN KEY(EMPLOYEEGUID) REFERENCES  
    GRATLYDB.SRC_EMPLOYEES(EMPLOYEEGUID)
  ); 

-- This Table stores user info from signup page for application and is a master table

  CREATE TABLE IF NOT EXISTS GRATLYDB.USER_MASTER (
    USERID INT AUTO_INCREMENT PRIMARY KEY,
    FIRSTNAME VARCHAR(32) NOT NULL,
    LASTNAME VARCHAR(32) NOT NULL,
    EMAIL VARCHAR(64) NOT NULL UNIQUE,
    PHONENUMBER VARCHAR(32),
    PASSWORD_HASH VARCHAR(255) NOT NULL,
    USERSTATUS BOOLEAN,
    CREATEDAT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    USERSTATUS TINYINT(1) DEFAULT NULL
  );

-- This Table stores the association of the user to restaurant for all users 

  CREATE TABLE IF NOT EXISTS GRATLYDB.USERRESTAURANT (
   USERRESTAURANTID INT AUTO_INCREMENT PRIMARY KEY,
   USERID INT,
   RESTAURANTID INT,
   CONSTRAINT FK_RESID FOREIGN KEY(RESTAURANTID) REFERENCES  
   GRATLYDB.SRC_ONBOARDING(RESTAURANTID),
   CONSTRAINT FK_USERID FOREIGN KEY(USERID) REFERENCES  
   GRATLYDB.USER_MASTER(USERID)
  );

-- Astra onboarding tables

  CREATE TABLE IF NOT EXISTS GRATLYDB.ASTRA_RESTAURANTS (
        RESTAURANTID INT PRIMARY KEY,
        RESTAURANTGUID VARCHAR(36),
        NAME VARCHAR(255),
        STATUS ENUM('invited', 'onboarding', 'active', 'suspended') DEFAULT 'invited',
        CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
        UNIQUE KEY UNIQ_ASTRA_RESTAURANT_GUID (RESTAURANTGUID),
        CONSTRAINT FK_ASTRA_RESTAURANTID FOREIGN KEY(RESTAURANTID) REFERENCES
        GRATLYDB.SRC_ONBOARDING(RESTAURANTID)
  );

  CREATE TABLE IF NOT EXISTS GRATLYDB.ASTRA_EMPLOYEES (
        USERID INT PRIMARY KEY,
        RESTAURANTID INT,
        EMPLOYEEGUID VARCHAR(36),
        FNAME VARCHAR(64),
        LNAME VARCHAR(64),
        EMAIL VARCHAR(64),
        PHONE VARCHAR(12),
        STATUS ENUM('invited', 'active', 'inactive') DEFAULT 'invited',
        CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
        UNIQUE KEY UNIQ_ASTRA_EMPLOYEE_GUID (EMPLOYEEGUID),
        CONSTRAINT FK_ASTRA_EMPLOYEE_USERID FOREIGN KEY(USERID) REFERENCES
        GRATLYDB.USER_MASTER(USERID),
        CONSTRAINT FK_ASTRA_EMPLOYEE_RESTAURANTID FOREIGN KEY(RESTAURANTID) REFERENCES
        GRATLYDB.SRC_ONBOARDING(RESTAURANTID)
  );

  CREATE TABLE IF NOT EXISTS GRATLYDB.ASTRA_CONNECTIONS (
        ID CHAR(36) PRIMARY KEY,
        OWNER_TYPE ENUM('restaurant', 'employee') NOT NULL,
        OWNER_ID INT NOT NULL,
        ASTRA_USER_ID VARCHAR(255),
        ASTRA_BUSINESS_PROFILE_ID VARCHAR(255),
        KYX_TYPE VARCHAR(64),
        ONBOARDING_STATUS ENUM(
            'not_started', 'in_progress', 'pending_review', 'approved', 'rejected', 'errored'
        ) DEFAULT 'not_started',
        LAST_STATUS_REASON TEXT,
        ACCESS_TOKEN_ENCRYPTED TEXT,
        REFRESH_TOKEN_ENCRYPTED TEXT,
        ACCESS_TOKEN_EXPIRES_AT DATETIME,
        REVOKED_AT DATETIME,
        CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
        UNIQUE KEY UNIQ_ASTRA_CONNECTION_OWNER (OWNER_TYPE, OWNER_ID)
  );

  CREATE TABLE IF NOT EXISTS GRATLYDB.ASTRA_PAYOUT_METHODS (
        ID CHAR(36) PRIMARY KEY,
        OWNER_TYPE ENUM('restaurant', 'employee') NOT NULL,
        OWNER_ID INT NOT NULL,
        METHOD_TYPE ENUM('bank_account', 'debit_card') NOT NULL,
        ASTRA_ACCOUNT_ID VARCHAR(255),
        ASTRA_CARD_ID VARCHAR(255),
        LABEL VARCHAR(255),
        BRAND VARCHAR(64),
        LAST4 VARCHAR(8),
        STATUS ENUM('active', 'pending_verification', 'disabled', 'errored') DEFAULT 'pending_verification',
        IS_PREFERRED TINYINT(1) DEFAULT 0,
        CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
        UNIQUE KEY UNIQ_ASTRA_PAYOUT (OWNER_TYPE, OWNER_ID, ASTRA_ACCOUNT_ID, ASTRA_CARD_ID)
  );

  CREATE TABLE IF NOT EXISTS GRATLYDB.ASTRA_WEBHOOK_EVENTS (
        ID CHAR(36) PRIMARY KEY,
        ASTRA_EVENT_ID VARCHAR(255),
        EVENT_TYPE VARCHAR(255) NOT NULL,
        OWNER_TYPE ENUM('restaurant', 'employee'),
        OWNER_ID INT,
        PAYLOAD_JSON JSON,
        RECEIVED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        PROCESSED_AT TIMESTAMP NULL,
        PROCESSING_ERROR TEXT,
        UNIQUE KEY UNIQ_ASTRA_EVENT (ASTRA_EVENT_ID)
  );

CREATE TABLE IF NOT EXISTS GRATLYDB.MSTR_PERMISSIONS (
  PERMISSIONSID INT NOT NULL AUTO_INCREMENT,
  PERMISSIONSNAME VARCHAR(128) DEFAULT NULL,
  DELETED TINYINT(1) DEFAULT NULL,
  DISPLAY TINYINT(1) DEFAULT 1,
  CREATEDDATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  MODIFIEDDATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (PERMISSIONSID)
);

INSERT INTO GRATLYDB.MSTR_PERMISSIONS(PERMISSIONSNAME,DELETED,DISPLAY)
SELECT 'Create Payout Schedules',0,1
WHERE NOT EXISTS (
  SELECT 1 FROM GRATLYDB.MSTR_PERMISSIONS WHERE PERMISSIONSNAME = 'Create Payout Schedules'
);
INSERT INTO GRATLYDB.MSTR_PERMISSIONS(PERMISSIONSNAME,DELETED,DISPLAY)
SELECT 'Approve Payouts',0,1
WHERE NOT EXISTS (
  SELECT 1 FROM GRATLYDB.MSTR_PERMISSIONS WHERE PERMISSIONSNAME = 'Approve Payouts'
);
INSERT INTO GRATLYDB.MSTR_PERMISSIONS(PERMISSIONSNAME,DELETED,DISPLAY)
SELECT 'Manage Team',0,1
WHERE NOT EXISTS (
  SELECT 1 FROM GRATLYDB.MSTR_PERMISSIONS WHERE PERMISSIONSNAME = 'Manage Team'
);
INSERT INTO GRATLYDB.MSTR_PERMISSIONS(PERMISSIONSNAME,DELETED,DISPLAY)
SELECT 'Admin Access',0,1
WHERE NOT EXISTS (
  SELECT 1 FROM GRATLYDB.MSTR_PERMISSIONS WHERE PERMISSIONSNAME = 'Admin Access'
);
INSERT INTO GRATLYDB.MSTR_PERMISSIONS(PERMISSIONSNAME,DELETED,DISPLAY)
SELECT 'Superadmin Access',0,0
WHERE NOT EXISTS (
  SELECT 1 FROM GRATLYDB.MSTR_PERMISSIONS WHERE PERMISSIONSNAME = 'Superadmin Access'
);
INSERT INTO GRATLYDB.MSTR_PERMISSIONS(PERMISSIONSNAME,DELETED,DISPLAY)
SELECT 'Employee Only',0,1
WHERE NOT EXISTS (
  SELECT 1 FROM GRATLYDB.MSTR_PERMISSIONS WHERE PERMISSIONSNAME = 'Employee Only'
);
INSERT INTO GRATLYDB.MSTR_PERMISSIONS(PERMISSIONSNAME,DELETED,DISPLAY)
SELECT 'Manager Access',0,1
WHERE NOT EXISTS (
  SELECT 1 FROM GRATLYDB.MSTR_PERMISSIONS WHERE PERMISSIONSNAME = 'Manager Access'
);
INSERT INTO GRATLYDB.MSTR_PERMISSIONS(PERMISSIONSNAME,DELETED,DISPLAY)
SELECT 'Report for Payroll',0,1
WHERE NOT EXISTS (
  SELECT 1 FROM GRATLYDB.MSTR_PERMISSIONS WHERE PERMISSIONSNAME = 'Report for Payroll'
);

ALTER TABLE GRATLYDB.MSTR_PERMISSIONS
  ADD COLUMN DISPLAY TINYINT(1) DEFAULT 1;

UPDATE GRATLYDB.MSTR_PERMISSIONS
SET DISPLAY = 1
WHERE DISPLAY IS NULL;

UPDATE GRATLYDB.MSTR_PERMISSIONS
SET DISPLAY = 0
WHERE PERMISSIONSNAME = 'Superadmin Access';

-- This Table stores the permissions for all users

CREATE TABLE IF NOT EXISTS GRATLYDB.USER_PERMISSIONS(
  USERPERMISSIONSID INT AUTO_INCREMENT PRIMARY KEY, 
  USERID INT,
  PERMISSIONSID INT,
  CREATEDDATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  MODIFIEDDATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT FK_USERID_UP FOREIGN KEY(USERID) REFERENCES  
    GRATLYDB.USER_MASTER(USERID),
  CONSTRAINT FK_PERMISSIONSID_UP FOREIGN KEY(PERMISSIONSID) REFERENCES  
    GRATLYDB.MSTR_PERMISSIONS(PERMISSIONSID)
);

-- Below tables will store ALL values for Payout Schedule created for each restaurant

CREATE TABLE IF NOT EXISTS GRATLYDB.PAYOUT_SCHEDULE (
PAYOUT_SCHEDULEID INT AUTO_INCREMENT PRIMARY KEY,
RESTAURANTID INT NOT NULL,
USERID INT NOT NULL,
NAME VARCHAR(128) NOT NULL,
START_DAY VARCHAR(8),
END_DAY VARCHAR(8),
START_TIME VARCHAR(8),
END_TIME VARCHAR(8),
PAYOUTTRIGGER_GRATUITY FLOAT,
PAYOUTTRIGGER_TIPS FLOAT,
PAYOUT_RULE_ID VARCHAR(64) NOT NULL, -- 1 - CUSTOM PAYOUT, 2 - EQUAL PAYOUT, 3 - HOUR BASED PAYOUT, 4 - JOB WEIGHTED PAYOUT
PREPAYOUT_FLAG BOOLEAN,              -- 1 - VALUE EXISTS FOR PRE_PAYOUT, 0 - NO VALUE FOR PREPAYOUT
CREATEDDATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
MODIFIEDDATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
CONSTRAINT FK_PAYOUT_RESTAURANTID FOREIGN KEY(RESTAURANTID) REFERENCES GRATLYDB.SRC_ONBOARDING(RESTAURANTID),
CONSTRAINT FK_PAYOUT_USERID FOREIGN KEY(USERID) REFERENCES GRATLYDB.USER_MASTER(USERID)
);



CREATE TABLE IF NOT EXISTS GRATLYDB.PAYOUTRECEIVERS (
PAYOUTRECEIVERSID INT AUTO_INCREMENT PRIMARY KEY,
PAYOUT_SCHEDULEID INT,
PAYOUT_RULE_ID VARCHAR(64),
CONTRIBUTOR_RECIEVER BOOLEAN,
PAYOUT_RECEIVERID VARCHAR(36),
PAYOUT_PERCENTAGE FLOAT,
CREATEDDATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
MODIFIEDDATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
CONSTRAINT FK_PAYOUT_SCHEDULEID FOREIGN KEY(PAYOUT_SCHEDULEID) REFERENCES GRATLYDB.PAYOUT_SCHEDULE(PAYOUT_SCHEDULEID)
);


CREATE TABLE IF NOT EXISTS GRATLYDB.PAYOUT_CUSTOM (
PAYOUT_CUSTOMID  INT AUTO_INCREMENT PRIMARY KEY,
PAYOUT_SCHEDULEID INT,
INDIVIDUAL_PAYOUT FLOAT,
GROUPCONTRIBUTION FLOAT,
CREATEDDATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
MODIFIEDDATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
CONSTRAINT FK_PAYOUT_SCHEDULEID_PC FOREIGN KEY(PAYOUT_SCHEDULEID) REFERENCES GRATLYDB.PAYOUT_SCHEDULE(PAYOUT_SCHEDULEID)
);

CREATE TABLE IF NOT EXISTS GRATLYDB.PREPAYOUT (
PREPAYOUTID INT AUTO_INCREMENT PRIMARY KEY,
PAYOUT_SCHEDULEID INT,
PREPAYOUTOPTION BOOLEAN, -- 0 MEANS PERCENTAGE AND 1 MEANS FIXED AMOUNT
PREPAYOUT_VALUE FLOAT,
USERACCOUNT VARCHAR(36),
CREATEDDATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
MODIFIEDDATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
CONSTRAINT FK_PAYOUT_SCHEDULEID_PP FOREIGN KEY(PAYOUT_SCHEDULEID) REFERENCES GRATLYDB.PAYOUT_SCHEDULE(PAYOUT_SCHEDULEID)
);

CREATE TABLE IF NOT EXISTS GRATLYDB.EMAIL_INVITES (
INVITEID INT AUTO_INCREMENT PRIMARY KEY,
USERID INT NOT NULL,
EMPLOYEEGUID VARCHAR(64),
EMAIL VARCHAR(128) NOT NULL,
FIRSTNAME VARCHAR(64),
LASTNAME VARCHAR(64),
STATUS VARCHAR(32) NOT NULL,
PROVIDER VARCHAR(32),
PROVIDER_RESPONSE TEXT,
CREATEDDATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
MODIFIEDDATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
INDEX IDX_EMAIL_INVITES_USERID (USERID),
INDEX IDX_EMAIL_INVITES_EMAIL (EMAIL),
CONSTRAINT FK_EMAIL_INVITES_USERID FOREIGN KEY(USERID) REFERENCES GRATLYDB.USER_MASTER(USERID)
);

CREATE TABLE IF NOT EXISTS GRATLYDB.PAYOUT_APPROVAL (
PAYOUT_APPROVALID INT AUTO_INCREMENT PRIMARY KEY,
RESTAURANTID INT NOT NULL,
PAYOUT_SCHEDULEID INT NOT NULL,
BUSINESSDATE VARCHAR(32) NOT NULL,
IS_APPROVED TINYINT(1) NOT NULL DEFAULT 0,
UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
UNIQUE KEY uq_payout_approval (RESTAURANTID, PAYOUT_SCHEDULEID, BUSINESSDATE)
);

CREATE TABLE IF NOT EXISTS GRATLYDB.PAYOUT_APPROVAL_ITEMS (
PAYOUT_APPROVAL_ITEMID INT AUTO_INCREMENT PRIMARY KEY,
PAYOUT_APPROVALID INT NOT NULL,
RESTAURANTID INT NOT NULL,
PAYOUT_SCHEDULEID INT NOT NULL,
BUSINESSDATE VARCHAR(32) NOT NULL,
EMPLOYEEGUID VARCHAR(36),
EMPLOYEE_NAME VARCHAR(128),
JOBTITLE VARCHAR(128),
IS_CONTRIBUTOR VARCHAR(8),
PAYOUT_RECEIVER_ID VARCHAR(128),
PAYOUT_PERCENTAGE DECIMAL(10,2),
TOTAL_SALES DECIMAL(12,2),
NET_SALES DECIMAL(12,2),
TOTAL_TIPS DECIMAL(12,2),
TOTAL_GRATUITY DECIMAL(12,2),
OVERALL_TIPS DECIMAL(12,2),
OVERALL_GRATUITY DECIMAL(12,2),
PAYOUT_TIPS DECIMAL(12,2),
PAYOUT_GRATUITY DECIMAL(12,2),
NET_PAYOUT DECIMAL(12,2),
UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
UNIQUE KEY UQ_PAYOUT_APPROVAL_ITEM (PAYOUT_APPROVALID, EMPLOYEEGUID, JOBTITLE, IS_CONTRIBUTOR),
CONSTRAINT FK_PAYOUT_APPROVAL_ITEM FOREIGN KEY(PAYOUT_APPROVALID)
REFERENCES GRATLYDB.PAYOUT_APPROVAL(PAYOUT_APPROVALID)
ON DELETE CASCADE
);

-- This script store the final approved Payout Schedule details

CREATE TABLE IF NOT EXISTS GRATLYDB.PAYOUT_FINAL (
PAYOUT_FINALID INT AUTO_INCREMENT PRIMARY KEY,
PAYOUT_APPROVALID INT NOT NULL,
RESTAURANTID INT NOT NULL,
PAYOUT_SCHEDULEID INT NOT NULL,
BUSINESSDATE VARCHAR(32) NOT NULL,
EMPLOYEEGUID VARCHAR(36),
EMPLOYEE_NAME VARCHAR(128),
JOBTITLE VARCHAR(128),
IS_CONTRIBUTOR VARCHAR(8),
PAYOUT_RECEIVER_ID VARCHAR(128),
PAYOUT_PERCENTAGE DECIMAL(10,2),
TOTAL_SALES DECIMAL(12,2),
NET_SALES DECIMAL(12,2),
TOTAL_TIPS DECIMAL(12,2),
TOTAL_GRATUITY DECIMAL(12,2),
OVERALL_TIPS DECIMAL(12,2),
OVERALL_GRATUITY DECIMAL(12,2),
PAYOUT_TIPS DECIMAL(12,2),
PAYOUT_GRATUITY DECIMAL(12,2),
NET_PAYOUT DECIMAL(12,2),
PREPAYOUT_DEDUCTION DECIMAL(12,2),
APPROVED_USERID INT NOT NULL,
UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
UNIQUE KEY UQ_PAYOUT_FINAL (PAYOUT_APPROVALID, EMPLOYEEGUID, JOBTITLE, IS_CONTRIBUTOR),
CONSTRAINT FK_PAYOUT_FINAL FOREIGN KEY(PAYOUT_APPROVALID) REFERENCES GRATLYDB.PAYOUT_APPROVAL(PAYOUT_APPROVALID));

-- Stripe billing tables

ALTER TABLE GRATLYDB.SRC_ONBOARDING
  ADD COLUMN STRIPE_ACCOUNT_ID VARCHAR(255) UNIQUE;

CREATE TABLE IF NOT EXISTS GRATLYDB.BILLING_CONFIG (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  CONFIG_KEY VARCHAR(64) NOT NULL UNIQUE,
  CONFIG_VALUE VARCHAR(255) NOT NULL,
  UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS GRATLYDB.STRIPE_CUSTOMERS (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  BUSINESS_ID INT NOT NULL,
  STRIPE_CUSTOMER_ID VARCHAR(255) NOT NULL,
  CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY UNIQ_STRIPE_CUSTOMER_BUSINESS (BUSINESS_ID),
  UNIQUE KEY UNIQ_STRIPE_CUSTOMER_ID (STRIPE_CUSTOMER_ID),
  CONSTRAINT FK_STRIPE_CUSTOMERS_BUSINESS FOREIGN KEY(BUSINESS_ID)
    REFERENCES GRATLYDB.SRC_ONBOARDING(RESTAURANTID)
);

CREATE TABLE IF NOT EXISTS GRATLYDB.BILLING_SUBSCRIPTIONS (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  BUSINESS_ID INT NOT NULL,
  STRIPE_SUBSCRIPTION_ID VARCHAR(255) NOT NULL,
  STATUS VARCHAR(32) NOT NULL,
  PRICE_ID VARCHAR(255) NOT NULL,
  CURRENT_PERIOD_START DATETIME NULL,
  CURRENT_PERIOD_END DATETIME NULL,
  CANCEL_AT_PERIOD_END BOOLEAN NOT NULL DEFAULT 0,
  TRIAL_END DATETIME NULL,
  DEFAULT_PAYMENT_METHOD_BRAND VARCHAR(32) NULL,
  DEFAULT_PAYMENT_METHOD_LAST4 VARCHAR(4) NULL,
  CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY UNIQ_BILLING_SUB_BUSINESS (BUSINESS_ID),
  UNIQUE KEY UNIQ_BILLING_SUB_STRIPE (STRIPE_SUBSCRIPTION_ID),
  CONSTRAINT FK_BILLING_SUBSCRIPTION_BUSINESS FOREIGN KEY(BUSINESS_ID)
    REFERENCES GRATLYDB.SRC_ONBOARDING(RESTAURANTID)
);

CREATE TABLE IF NOT EXISTS GRATLYDB.INVOICE_RECORDS (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  BUSINESS_ID INT NOT NULL,
  STRIPE_INVOICE_ID VARCHAR(255) NOT NULL UNIQUE,
  NUMBER VARCHAR(255) NULL,
  STATUS VARCHAR(32) NOT NULL,
  AMOUNT_DUE BIGINT NOT NULL,
  AMOUNT_PAID BIGINT NOT NULL,
  CURRENCY VARCHAR(8) NOT NULL,
  HOSTED_INVOICE_URL TEXT NULL,
  INVOICE_PDF TEXT NULL,
  CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
  INDEX IDX_INVOICE_RECORDS_BUSINESS (BUSINESS_ID),
  CONSTRAINT FK_INVOICE_RECORDS_BUSINESS FOREIGN KEY(BUSINESS_ID)
    REFERENCES GRATLYDB.SRC_ONBOARDING(RESTAURANTID)
);

CREATE TABLE IF NOT EXISTS GRATLYDB.PLAN_PRICES (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  BUSINESS_ID INT NOT NULL,
  PLAN_KEY VARCHAR(32) NOT NULL,
  PRICE_ID VARCHAR(255) NOT NULL,
  UNIQUE KEY UNIQ_PLAN_PRICE_BUSINESS (BUSINESS_ID, PLAN_KEY),
  INDEX IDX_PLAN_PRICE_BUSINESS (BUSINESS_ID),
  CONSTRAINT FK_PLAN_PRICES_BUSINESS FOREIGN KEY(BUSINESS_ID)
    REFERENCES GRATLYDB.SRC_ONBOARDING(RESTAURANTID)
);
