
-- This syntax will create the new DB

  CREATE DATABASE IF NOT EXISTS GRATLYDB;


-- This table is the first table created after customer is onboarded

  CREATE TABLE IF NOT EXISTS GRATLYDB.SRC_ONBOARDING (
         RESTAURANTID INT AUTO_INCREMENT PRIMARY KEY,
         RESTAURANTGUID VARCHAR(36) NOT NULL,
         SECRETKEY VARCHAR(256),
         CLIENTSECRET VARCHAR(256),
         USERACCESSTYPE VARCHAR(64),
         PAYOUT_THRESHOLD_CENTS INT,
         TIMEZONE VARCHAR(128),
         PAYOUT_FEE_PAYER VARCHAR(32),
         PAYOUT_FEE VARCHAR(32),
         ACTIVATION_DATE DATE,
         FREE_PERIOD VARCHAR(32),
         BILLING_DATE DATE,
         BILLING_AMOUNT VARCHAR(32),
         ADMIN_NAME VARCHAR(128),
         ADMIN_PHONE VARCHAR(32),
         ADMIN_EMAIL VARCHAR(128)
     );

ALTER TABLE GRATLYDB.SRC_ONBOARDING AUTO_INCREMENT = 100;

-- Ensure all required columns exist in SRC_ONBOARDING (migration for production database)
SET @col_exists := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA='GRATLYDB' AND TABLE_NAME='SRC_ONBOARDING' AND COLUMN_NAME='SECRETKEY');
SET @sql := IF(@col_exists = 0, 'ALTER TABLE GRATLYDB.SRC_ONBOARDING ADD COLUMN SECRETKEY VARCHAR(256)', 'SELECT 1');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @col_exists := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA='GRATLYDB' AND TABLE_NAME='SRC_ONBOARDING' AND COLUMN_NAME='CLIENTSECRET');
SET @sql := IF(@col_exists = 0, 'ALTER TABLE GRATLYDB.SRC_ONBOARDING ADD COLUMN CLIENTSECRET VARCHAR(256)', 'SELECT 1');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @col_exists := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA='GRATLYDB' AND TABLE_NAME='SRC_ONBOARDING' AND COLUMN_NAME='USERACCESSTYPE');
SET @sql := IF(@col_exists = 0, 'ALTER TABLE GRATLYDB.SRC_ONBOARDING ADD COLUMN USERACCESSTYPE VARCHAR(64)', 'SELECT 1');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @col_exists := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA='GRATLYDB' AND TABLE_NAME='SRC_ONBOARDING' AND COLUMN_NAME='PAYOUT_THRESHOLD_CENTS');
SET @sql := IF(@col_exists = 0, 'ALTER TABLE GRATLYDB.SRC_ONBOARDING ADD COLUMN PAYOUT_THRESHOLD_CENTS INT', 'SELECT 1');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @col_exists := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA='GRATLYDB' AND TABLE_NAME='SRC_ONBOARDING' AND COLUMN_NAME='TIMEZONE');
SET @sql := IF(@col_exists = 0, 'ALTER TABLE GRATLYDB.SRC_ONBOARDING ADD COLUMN TIMEZONE VARCHAR(128)', 'SELECT 1');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @col_exists := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA='GRATLYDB' AND TABLE_NAME='SRC_ONBOARDING' AND COLUMN_NAME='PAYOUT_FEE_PAYER');
SET @sql := IF(@col_exists = 0, 'ALTER TABLE GRATLYDB.SRC_ONBOARDING ADD COLUMN PAYOUT_FEE_PAYER VARCHAR(32)', 'SELECT 1');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @col_exists := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA='GRATLYDB' AND TABLE_NAME='SRC_ONBOARDING' AND COLUMN_NAME='PAYOUT_FEE');
SET @sql := IF(@col_exists = 0, 'ALTER TABLE GRATLYDB.SRC_ONBOARDING ADD COLUMN PAYOUT_FEE VARCHAR(32)', 'SELECT 1');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @col_exists := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA='GRATLYDB' AND TABLE_NAME='SRC_ONBOARDING' AND COLUMN_NAME='ACTIVATION_DATE');
SET @sql := IF(@col_exists = 0, 'ALTER TABLE GRATLYDB.SRC_ONBOARDING ADD COLUMN ACTIVATION_DATE DATE', 'SELECT 1');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @col_exists := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA='GRATLYDB' AND TABLE_NAME='SRC_ONBOARDING' AND COLUMN_NAME='FREE_PERIOD');
SET @sql := IF(@col_exists = 0, 'ALTER TABLE GRATLYDB.SRC_ONBOARDING ADD COLUMN FREE_PERIOD VARCHAR(32)', 'SELECT 1');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @col_exists := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA='GRATLYDB' AND TABLE_NAME='SRC_ONBOARDING' AND COLUMN_NAME='BILLING_DATE');
SET @sql := IF(@col_exists = 0, 'ALTER TABLE GRATLYDB.SRC_ONBOARDING ADD COLUMN BILLING_DATE DATE', 'SELECT 1');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @col_exists := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA='GRATLYDB' AND TABLE_NAME='SRC_ONBOARDING' AND COLUMN_NAME='BILLING_AMOUNT');
SET @sql := IF(@col_exists = 0, 'ALTER TABLE GRATLYDB.SRC_ONBOARDING ADD COLUMN BILLING_AMOUNT VARCHAR(32)', 'SELECT 1');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @col_exists := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA='GRATLYDB' AND TABLE_NAME='SRC_ONBOARDING' AND COLUMN_NAME='ADMIN_NAME');
SET @sql := IF(@col_exists = 0, 'ALTER TABLE GRATLYDB.SRC_ONBOARDING ADD COLUMN ADMIN_NAME VARCHAR(128)', 'SELECT 1');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @col_exists := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA='GRATLYDB' AND TABLE_NAME='SRC_ONBOARDING' AND COLUMN_NAME='ADMIN_PHONE');
SET @sql := IF(@col_exists = 0, 'ALTER TABLE GRATLYDB.SRC_ONBOARDING ADD COLUMN ADMIN_PHONE VARCHAR(32)', 'SELECT 1');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @col_exists := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA='GRATLYDB' AND TABLE_NAME='SRC_ONBOARDING' AND COLUMN_NAME='ADMIN_EMAIL');
SET @sql := IF(@col_exists = 0, 'ALTER TABLE GRATLYDB.SRC_ONBOARDING ADD COLUMN ADMIN_EMAIL VARCHAR(128)', 'SELECT 1');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

-- INSERT INTO GRATLYDB.SRC_ONBOARDING(RESTAURANTGUID ,SECRETKEY, CLIENTSECRET, USERACCESSTYPE) values('0169bd32-becf-4b04-9093-d7d4db1dc242','WZ8mobWCpK4AcXQjDHgZcgQIMOCaQ3xs','XsplfAXitqH1ePen0nkEWV_lFuCEaabjEPhpagi_zLlKxDVdIrPdwhWJgj0W2o2v','TOAST_MACHINE_CLIENT');

-- This script will store the details of the restaurant(s) and is a source table

  CREATE TABLE IF NOT EXISTS GRATLYDB.SRC_RESTAURANTDETAILS(
        RESTAURANTGUID VARCHAR(36) PRIMARY KEY,
        RESTAURANTNAME VARCHAR(128) NOT NULL,
        LOCATIONNAME VARCHAR(128),
        LOCATIONCODE VARCHAR(64),
        DESCRIPTION VARCHAR(128),
        TIMEZONE VARCHAR(128),
        CURRENCYCODE VARCHAR(32),
        FIRSTBUSINESSDATE VARCHAR(16),
        ARCHIVED VARCHAR(8),
        ADDRESS1 VARCHAR(256),
        ADDRESS2 VARCHAR(256),
        CITY VARCHAR(32),
        STATECODE VARCHAR(16),
        ZIPCODE VARCHAR(8),
        COUNTRY VARCHAR(32),
        PHONE VARCHAR(16),
        WEBSITE VARCHAR(512),
        ORDERONLINE VARCHAR(512)
  );

-- This script will store the details of all employees for all restaurants and is a source table

  CREATE TABLE IF NOT EXISTS GRATLYDB.SRC_EMPLOYEES (
        RESTAURANTGUID VARCHAR(36) ,
        EMPLOYEEGUID VARCHAR(36) NOT NULL UNIQUE,
        EMPLOYEEFNAME VARCHAR(64),
        EMPLOYEELNAME VARCHAR(64),
        CHOSENNAME VARCHAR(64),
        PHONENUMBER VARCHAR(16),
        EMAIL VARCHAR(64),
        DELETED VARCHAR(8),
        DELETEDDATE DATE,
        PRIMARY KEY (RESTAURANTGUID, EMPLOYEEGUID),
        CONSTRAINT FK_RESGUIDEMP FOREIGN KEY(RESTAURANTGUID) REFERENCES  
        GRATLYDB.SRC_RESTAURANTDETAILS(RESTAURANTGUID)

  );
-- This table stores all different type of jobs for all the restaurants and is a source table

  CREATE TABLE IF NOT EXISTS GRATLYDB.SRC_JOBS (
        RESTAURANTGUID VARCHAR(36),
        JOBGUID VARCHAR(36) NOT NULL UNIQUE,
        JOBTITLE VARCHAR(64),
        ENTITYTYPE VARCHAR(32),
        CREATEDDATE DATE,
        DELETED VARCHAR(8),
        DELETEDDATE DATE,
        CODE VARCHAR(36),
        TIPPED VARCHAR(8),
        DEFAULTWAGE VARCHAR(32),
        WAGEFREQUENCY VARCHAR(32),
        PRIMARY KEY (RESTAURANTGUID,JOBGUID),
        CONSTRAINT FK_RESGUIDJOB FOREIGN KEY(RESTAURANTGUID) REFERENCES  
        GRATLYDB.SRC_RESTAURANTDETAILS(RESTAURANTGUID)
  );


-- This table stores all roles assigned to an employee by the Restaurant and is a source table

  CREATE TABLE IF NOT EXISTS GRATLYDB.SRC_EMPLOYEEROLE (
        RESTAURANTGUID VARCHAR(36),
        EMPLOYEEGUID VARCHAR(36),
        NAME VARCHAR(64),
        JOBGUID varchar(36),
        PRIMARY KEY(RESTAURANTGUID,EMPLOYEEGUID,JOBGUID),
        CONSTRAINT FK_RESGUIDEMPR FOREIGN KEY(RESTAURANTGUID) REFERENCES  
        GRATLYDB.SRC_RESTAURANTDETAILS(RESTAURANTGUID),
        CONSTRAINT FK_EMPGUID FOREIGN KEY(EMPLOYEEGUID) REFERENCES  
        GRATLYDB.SRC_EMPLOYEES(EMPLOYEEGUID),
        CONSTRAINT FK_JOBGUID FOREIGN KEY(JOBGUID) REFERENCES  
        GRATLYDB.SRC_JOBS(JOBGUID)
  );

-- This script stores all tables in the restaurant and is a source table

  CREATE TABLE IF NOT EXISTS GRATLYDB.SRC_TABLES (
     RESTAURANTGUID VARCHAR(36),		
     TABLEGUID VARCHAR(36),
     ENTITYTYPE VARCHAR(16),
     TABLENAME VARCHAR(32),
     PRIMARY KEY(RESTAURANTGUID,TABLEGUID),
     CONSTRAINT FK_RESGUIDTAB FOREIGN KEY(RESTAURANTGUID) REFERENCES  
     GRATLYDB.SRC_RESTAURANTDETAILS(RESTAURANTGUID)
  );

-- This table get all time entries for all employees for the current day and is a source table

  CREATE TABLE IF NOT EXISTS GRATLYDB.SRC_TIMEENTRIES (
    RESTAURANTGUID VARCHAR(36),		
    TIMEENTRYGUID VARCHAR(36),
    ENTITYTYPE VARCHAR(50) NOT NULL,
    EXTERNALID VARCHAR(255),
    EMPLOYEEGUID VARCHAR(36),
    JOBID VARCHAR(36),
    SHIFTREFERENCE VARCHAR(36),
    INDATE VARCHAR(36),
    OUTDATE VARCHAR(36),
    BUSINESSDATE VARCHAR(12),
    REGULARHOURS DECIMAL(5,2) DEFAULT 0.00,
    OVERTIMEHOURS DECIMAL(5,2) DEFAULT 0.00,
    HOURLYWAGE DECIMAL(7,2),
    TIPSWITHHELD DECIMAL(7,2) DEFAULT 0.00,
    NONCASHSALES DECIMAL(10,2) DEFAULT 0.00,
    CASHSALES DECIMAL(10,2) DEFAULT 0.00,
    NONCASHGRATUITYSERVICECHARGES DECIMAL(10,2) DEFAULT 0.00,
    CASHGRATUITYSERVICECHARGES DECIMAL(10,2) DEFAULT 0.00,
    NONCASHTIPS DECIMAL(5,2),
    DECLAREDCASHTIPS DECIMAL(10,2),
    AUTOCLOCKEDOUT BOOLEAN DEFAULT FALSE,
    DELETED BOOLEAN DEFAULT FALSE,
    CREATEDDATE VARCHAR(36),
    MODIFIEDDATE VARCHAR(36),
    DELETEDDATE VARCHAR(36),
    PRIMARY KEY (RESTAURANTGUID,TIMEENTRYGUID),
    CONSTRAINT FK_RESGUIDTME FOREIGN KEY(RESTAURANTGUID) REFERENCES  
    GRATLYDB.SRC_RESTAURANTDETAILS(RESTAURANTGUID),
    CONSTRAINT FK_EMPGUIDTME FOREIGN KEY(EMPLOYEEGUID) REFERENCES  
    GRATLYDB.SRC_EMPLOYEES(EMPLOYEEGUID)
  );

-- This table contains all orders for current day for all restaurants and is a source table

  CREATE TABLE IF NOT EXISTS GRATLYDB.SRC_ALLORDERS (
    RESTAURANTGUID VARCHAR(36),
    ORDERGUID VARCHAR(36),
    DISPLAYNUMBER INT,
    BUSINESSDATE VARCHAR(12),
    ORDERSOURCE VARCHAR(64),
    TABLEGUID VARCHAR(36),
    ORDERPAIDDATE VARCHAR(36),
    VOIDED VARCHAR(8),
    OPENEDDATE VARCHAR(36),
    PREPTIME VARCHAR(32),
    PAYMENTTYPE VARCHAR(16),
    REFUNDSTATUS VARCHAR(16),
    PAYMENTSTATUS VARCHAR(16),
    NETAMOUNT DECIMAL(7,2),
    TIPAMOUNT DECIMAL(5,2),
    GRATUITYAMOUNT DECIMAL(5,2),
    TAXAMOUNT DECIMAL(7,2),
    TOTALAMOUNT DECIMAL(7,2),
    EMPLOYEEGUID VARCHAR(36),
    NUMBEROFGUESTS INT,
    DURATION BIGINT,
    APPROVALSTATUS VARCHAR(16),
    PRIMARY KEY (RESTAURANTGUID,ORDERGUID),
    CONSTRAINT FK_RESGUIDALO FOREIGN KEY(RESTAURANTGUID) REFERENCES  
    GRATLYDB.SRC_RESTAURANTDETAILS(RESTAURANTGUID),
    CONSTRAINT FK_EMPGUIDALO FOREIGN KEY(EMPLOYEEGUID) REFERENCES  
    GRATLYDB.SRC_EMPLOYEES(EMPLOYEEGUID)
  ); 

-- This Table stores user info from signup page for application and is a master table

  CREATE TABLE IF NOT EXISTS GRATLYDB.USER_MASTER (
    USERID INT AUTO_INCREMENT PRIMARY KEY,
    FIRSTNAME VARCHAR(32) NOT NULL,
    LASTNAME VARCHAR(32) NOT NULL,
    EMAIL VARCHAR(64) NOT NULL UNIQUE,
    PHONENUMBER VARCHAR(32),
    PASSWORD_HASH VARCHAR(255) NOT NULL,
    USERSTATUS BOOLEAN,
    CREATEDAT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    USERSTATUS TINYINT(1) DEFAULT NULL
  );

-- This Table stores the association of the user to restaurant for all users 

  CREATE TABLE IF NOT EXISTS GRATLYDB.USERRESTAURANT (
   USERRESTAURANTID INT AUTO_INCREMENT PRIMARY KEY,
   USERID INT,
   RESTAURANTID INT,
   CONSTRAINT FK_RESID FOREIGN KEY(RESTAURANTID) REFERENCES  
   GRATLYDB.SRC_ONBOARDING(RESTAURANTID),
   CONSTRAINT FK_USERID FOREIGN KEY(USERID) REFERENCES  
   GRATLYDB.USER_MASTER(USERID)
  );

-- Moov replaces Astra + Stripe for onboarding and payments

CREATE TABLE IF NOT EXISTS GRATLYDB.MSTR_PERMISSIONS (
  PERMISSIONSID INT NOT NULL AUTO_INCREMENT,
  PERMISSIONSNAME VARCHAR(128) DEFAULT NULL,
  DELETED TINYINT(1) DEFAULT NULL,
  DISPLAY TINYINT(1) DEFAULT 1,
  CREATEDDATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  MODIFIEDDATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (PERMISSIONSID)
);

INSERT INTO GRATLYDB.MSTR_PERMISSIONS(PERMISSIONSNAME,DELETED,DISPLAY)
SELECT 'Create Payout Schedules',0,1
WHERE NOT EXISTS (
  SELECT 1 FROM GRATLYDB.MSTR_PERMISSIONS WHERE PERMISSIONSNAME = 'Create Payout Schedules'
);
INSERT INTO GRATLYDB.MSTR_PERMISSIONS(PERMISSIONSNAME,DELETED,DISPLAY)
SELECT 'Approve Payouts',0,1
WHERE NOT EXISTS (
  SELECT 1 FROM GRATLYDB.MSTR_PERMISSIONS WHERE PERMISSIONSNAME = 'Approve Payouts'
);
INSERT INTO GRATLYDB.MSTR_PERMISSIONS(PERMISSIONSNAME,DELETED,DISPLAY)
SELECT 'Manage Team',0,1
WHERE NOT EXISTS (
  SELECT 1 FROM GRATLYDB.MSTR_PERMISSIONS WHERE PERMISSIONSNAME = 'Manage Team'
);
INSERT INTO GRATLYDB.MSTR_PERMISSIONS(PERMISSIONSNAME,DELETED,DISPLAY)
SELECT 'Admin Access',0,1
WHERE NOT EXISTS (
  SELECT 1 FROM GRATLYDB.MSTR_PERMISSIONS WHERE PERMISSIONSNAME = 'Admin Access'
);
INSERT INTO GRATLYDB.MSTR_PERMISSIONS(PERMISSIONSNAME,DELETED,DISPLAY)
SELECT 'Superadmin Access',0,0
WHERE NOT EXISTS (
  SELECT 1 FROM GRATLYDB.MSTR_PERMISSIONS WHERE PERMISSIONSNAME = 'Superadmin Access'
);
INSERT INTO GRATLYDB.MSTR_PERMISSIONS(PERMISSIONSNAME,DELETED,DISPLAY)
SELECT 'Employee Only',0,1
WHERE NOT EXISTS (
  SELECT 1 FROM GRATLYDB.MSTR_PERMISSIONS WHERE PERMISSIONSNAME = 'Employee Only'
);
INSERT INTO GRATLYDB.MSTR_PERMISSIONS(PERMISSIONSNAME,DELETED,DISPLAY)
SELECT 'Manager Access',0,1
WHERE NOT EXISTS (
  SELECT 1 FROM GRATLYDB.MSTR_PERMISSIONS WHERE PERMISSIONSNAME = 'Manager Access'
);
INSERT INTO GRATLYDB.MSTR_PERMISSIONS(PERMISSIONSNAME,DELETED,DISPLAY)
SELECT 'Report for Payroll',0,1
WHERE NOT EXISTS (
  SELECT 1 FROM GRATLYDB.MSTR_PERMISSIONS WHERE PERMISSIONSNAME = 'Report for Payroll'
);

-- Add DISPLAY column if it doesn't exist
SET @col_exists := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA='GRATLYDB' AND TABLE_NAME='MSTR_PERMISSIONS' AND COLUMN_NAME='DISPLAY');

SET @sql := IF(@col_exists = 0, 'ALTER TABLE GRATLYDB.MSTR_PERMISSIONS ADD COLUMN DISPLAY TINYINT(1) DEFAULT 1', 'SELECT 1');

PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

UPDATE GRATLYDB.MSTR_PERMISSIONS
SET DISPLAY = 1
WHERE DISPLAY IS NULL;

UPDATE GRATLYDB.MSTR_PERMISSIONS
SET DISPLAY = 0
WHERE PERMISSIONSNAME = 'Superadmin Access';

-- This Table stores the permissions for all users

CREATE TABLE IF NOT EXISTS GRATLYDB.USER_PERMISSIONS(
  USERPERMISSIONSID INT AUTO_INCREMENT PRIMARY KEY, 
  USERID INT,
  PERMISSIONSID INT,
  CREATEDDATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  MODIFIEDDATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT FK_USERID_UP FOREIGN KEY(USERID) REFERENCES  
    GRATLYDB.USER_MASTER(USERID),
  CONSTRAINT FK_PERMISSIONSID_UP FOREIGN KEY(PERMISSIONSID) REFERENCES  
    GRATLYDB.MSTR_PERMISSIONS(PERMISSIONSID)
);

-- Below tables will store ALL values for Payout Schedule created for each restaurant

CREATE TABLE IF NOT EXISTS GRATLYDB.PAYOUT_SCHEDULE (
PAYOUT_SCHEDULEID INT AUTO_INCREMENT PRIMARY KEY,
RESTAURANTID INT NOT NULL,
USERID INT NOT NULL,
NAME VARCHAR(128) NOT NULL,
START_DAY VARCHAR(8),
END_DAY VARCHAR(8),
START_TIME VARCHAR(8),
END_TIME VARCHAR(8),
PAYOUTTRIGGER_GRATUITY FLOAT,
PAYOUTTRIGGER_TIPS FLOAT,
PAYOUT_RULE_ID VARCHAR(64) NOT NULL, -- 1 - CUSTOM PAYOUT, 2 - EQUAL PAYOUT, 3 - HOUR BASED PAYOUT, 4 - JOB WEIGHTED PAYOUT
PREPAYOUT_FLAG BOOLEAN,              -- 1 - VALUE EXISTS FOR PRE_PAYOUT, 0 - NO VALUE FOR PREPAYOUT
CREATEDDATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
MODIFIEDDATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
CONSTRAINT FK_PAYOUT_RESTAURANTID FOREIGN KEY(RESTAURANTID) REFERENCES GRATLYDB.SRC_ONBOARDING(RESTAURANTID),
CONSTRAINT FK_PAYOUT_USERID FOREIGN KEY(USERID) REFERENCES GRATLYDB.USER_MASTER(USERID)
);



CREATE TABLE IF NOT EXISTS GRATLYDB.PAYOUTRECEIVERS (
PAYOUTRECEIVERSID INT AUTO_INCREMENT PRIMARY KEY,
PAYOUT_SCHEDULEID INT,
PAYOUT_RULE_ID VARCHAR(64),
CONTRIBUTOR_RECIEVER BOOLEAN,
PAYOUT_RECEIVERID VARCHAR(36),
PAYOUT_PERCENTAGE FLOAT,
CREATEDDATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
MODIFIEDDATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
CONSTRAINT FK_PAYOUT_SCHEDULEID FOREIGN KEY(PAYOUT_SCHEDULEID) REFERENCES GRATLYDB.PAYOUT_SCHEDULE(PAYOUT_SCHEDULEID)
);


CREATE TABLE IF NOT EXISTS GRATLYDB.PAYOUT_CUSTOM (
PAYOUT_CUSTOMID  INT AUTO_INCREMENT PRIMARY KEY,
PAYOUT_SCHEDULEID INT,
INDIVIDUAL_PAYOUT FLOAT,
GROUPCONTRIBUTION FLOAT,
CREATEDDATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
MODIFIEDDATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
CONSTRAINT FK_PAYOUT_SCHEDULEID_PC FOREIGN KEY(PAYOUT_SCHEDULEID) REFERENCES GRATLYDB.PAYOUT_SCHEDULE(PAYOUT_SCHEDULEID)
);

CREATE TABLE IF NOT EXISTS GRATLYDB.PREPAYOUT (
PREPAYOUTID INT AUTO_INCREMENT PRIMARY KEY,
PAYOUT_SCHEDULEID INT,
PREPAYOUTOPTION BOOLEAN, -- 0 MEANS PERCENTAGE AND 1 MEANS FIXED AMOUNT
PREPAYOUT_VALUE FLOAT,
USERACCOUNT VARCHAR(36),
CREATEDDATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
MODIFIEDDATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
CONSTRAINT FK_PAYOUT_SCHEDULEID_PP FOREIGN KEY(PAYOUT_SCHEDULEID) REFERENCES GRATLYDB.PAYOUT_SCHEDULE(PAYOUT_SCHEDULEID)
);

CREATE TABLE IF NOT EXISTS GRATLYDB.EMAIL_INVITES (
INVITEID INT AUTO_INCREMENT PRIMARY KEY,
USERID INT NOT NULL,
EMPLOYEEGUID VARCHAR(64),
EMAIL VARCHAR(128) NOT NULL,
FIRSTNAME VARCHAR(64),
LASTNAME VARCHAR(64),
STATUS VARCHAR(32) NOT NULL,
PROVIDER VARCHAR(32),
PROVIDER_RESPONSE TEXT,
CREATEDDATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
MODIFIEDDATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
INDEX IDX_EMAIL_INVITES_USERID (USERID),
INDEX IDX_EMAIL_INVITES_EMAIL (EMAIL),
CONSTRAINT FK_EMAIL_INVITES_USERID FOREIGN KEY(USERID) REFERENCES GRATLYDB.USER_MASTER(USERID)
);

CREATE TABLE IF NOT EXISTS GRATLYDB.PAYOUT_APPROVAL (
PAYOUT_APPROVALID INT AUTO_INCREMENT PRIMARY KEY,
RESTAURANTID INT NOT NULL,
PAYOUT_SCHEDULEID INT NOT NULL,
BUSINESSDATE VARCHAR(32) NOT NULL,
IS_APPROVED TINYINT(1) NOT NULL DEFAULT 0,
UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
UNIQUE KEY uq_payout_approval (RESTAURANTID, PAYOUT_SCHEDULEID, BUSINESSDATE)
);

CREATE TABLE IF NOT EXISTS GRATLYDB.PAYOUT_APPROVAL_ITEMS (
PAYOUT_APPROVAL_ITEMID INT AUTO_INCREMENT PRIMARY KEY,
PAYOUT_APPROVALID INT NOT NULL,
RESTAURANTID INT NOT NULL,
PAYOUT_SCHEDULEID INT NOT NULL,
BUSINESSDATE VARCHAR(32) NOT NULL,
EMPLOYEEGUID VARCHAR(36),
EMPLOYEE_NAME VARCHAR(128),
JOBTITLE VARCHAR(128),
IS_CONTRIBUTOR VARCHAR(8),
PAYOUT_RECEIVER_ID VARCHAR(128),
PAYOUT_PERCENTAGE DECIMAL(10,2),
TOTAL_SALES DECIMAL(12,2),
NET_SALES DECIMAL(12,2),
TOTAL_TIPS DECIMAL(12,2),
TOTAL_GRATUITY DECIMAL(12,2),
OVERALL_TIPS DECIMAL(12,2),
OVERALL_GRATUITY DECIMAL(12,2),
PAYOUT_TIPS DECIMAL(12,2),
PAYOUT_GRATUITY DECIMAL(12,2),
NET_PAYOUT DECIMAL(12,2),
UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
UNIQUE KEY UQ_PAYOUT_APPROVAL_ITEM (PAYOUT_APPROVALID, EMPLOYEEGUID, JOBTITLE, IS_CONTRIBUTOR),
CONSTRAINT FK_PAYOUT_APPROVAL_ITEM FOREIGN KEY(PAYOUT_APPROVALID)
REFERENCES GRATLYDB.PAYOUT_APPROVAL(PAYOUT_APPROVALID)
ON DELETE CASCADE
);

-- This script store the final approved Payout Schedule details

CREATE TABLE IF NOT EXISTS GRATLYDB.PAYOUT_FINAL (
PAYOUT_FINALID INT AUTO_INCREMENT PRIMARY KEY,
PAYOUT_APPROVALID INT NOT NULL,
RESTAURANTID INT NOT NULL,
PAYOUT_SCHEDULEID INT NOT NULL,
BUSINESSDATE VARCHAR(32) NOT NULL,
EMPLOYEEGUID VARCHAR(36),
EMPLOYEE_NAME VARCHAR(128),
JOBTITLE VARCHAR(128),
IS_CONTRIBUTOR VARCHAR(8),
PAYOUT_RECEIVER_ID VARCHAR(128),
PAYOUT_PERCENTAGE DECIMAL(10,2),
TOTAL_SALES DECIMAL(12,2),
NET_SALES DECIMAL(12,2),
TOTAL_TIPS DECIMAL(12,2),
TOTAL_GRATUITY DECIMAL(12,2),
OVERALL_TIPS DECIMAL(12,2),
OVERALL_GRATUITY DECIMAL(12,2),
PAYOUT_TIPS DECIMAL(12,2),
PAYOUT_GRATUITY DECIMAL(12,2),
NET_PAYOUT DECIMAL(12,2),
PREPAYOUT_DEDUCTION DECIMAL(12,2),
PAID_STATUS VARCHAR(16) DEFAULT 'unpaid',
APPROVED_USERID INT NOT NULL,
UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
UNIQUE KEY UQ_PAYOUT_FINAL (PAYOUT_APPROVALID, EMPLOYEEGUID, JOBTITLE, IS_CONTRIBUTOR),
CONSTRAINT FK_PAYOUT_FINAL FOREIGN KEY(PAYOUT_APPROVALID) REFERENCES GRATLYDB.PAYOUT_APPROVAL(PAYOUT_APPROVALID));

-- Remove Stripe/Astra artifacts (destructive migration)
DROP TABLE IF EXISTS GRATLYDB.ASTRA_WEBHOOK_EVENTS;
DROP TABLE IF EXISTS GRATLYDB.ASTRA_PAYOUT_METHODS;
DROP TABLE IF EXISTS GRATLYDB.ASTRA_CONNECTIONS;
DROP TABLE IF EXISTS GRATLYDB.ASTRA_EMPLOYEES;
DROP TABLE IF EXISTS GRATLYDB.ASTRA_RESTAURANTS;
DROP TABLE IF EXISTS GRATLYDB.PLAN_PRICES;
DROP TABLE IF EXISTS GRATLYDB.INVOICE_RECORDS;
DROP TABLE IF EXISTS GRATLYDB.BILLING_SUBSCRIPTIONS;
DROP TABLE IF EXISTS GRATLYDB.STRIPE_CUSTOMERS;
DROP TABLE IF EXISTS GRATLYDB.BILLING_CONFIG;
-- Drop STRIPE_ACCOUNT_ID if it exists
SET @col_exists := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA='GRATLYDB' AND TABLE_NAME='SRC_ONBOARDING' AND COLUMN_NAME='STRIPE_ACCOUNT_ID');
SET @sql := IF(@col_exists > 0, 'ALTER TABLE GRATLYDB.SRC_ONBOARDING DROP COLUMN STRIPE_ACCOUNT_ID', 'SELECT 1');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

-- Add columns if they don't exist
SET @col_exists := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA='GRATLYDB' AND TABLE_NAME='SRC_ONBOARDING' AND COLUMN_NAME='PAYOUT_THRESHOLD_CENTS');
SET @sql := IF(@col_exists = 0, 'ALTER TABLE GRATLYDB.SRC_ONBOARDING ADD COLUMN PAYOUT_THRESHOLD_CENTS INT DEFAULT 5200', 'SELECT 1');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @col_exists := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA='GRATLYDB' AND TABLE_NAME='SRC_ONBOARDING' AND COLUMN_NAME='TIMEZONE');
SET @sql := IF(@col_exists = 0, 'ALTER TABLE GRATLYDB.SRC_ONBOARDING ADD COLUMN TIMEZONE VARCHAR(128)', 'SELECT 1');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @col_exists := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA='GRATLYDB' AND TABLE_NAME='PAYOUT_APPROVAL' AND COLUMN_NAME='APPROVED_AT');
SET @sql := IF(@col_exists = 0, 'ALTER TABLE GRATLYDB.PAYOUT_APPROVAL ADD COLUMN APPROVED_AT DATETIME NULL', 'SELECT 1');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @col_exists := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA='GRATLYDB' AND TABLE_NAME='PAYOUT_FINAL' AND COLUMN_NAME='APPROVED_AT');
SET @sql := IF(@col_exists = 0, 'ALTER TABLE GRATLYDB.PAYOUT_FINAL ADD COLUMN APPROVED_AT DATETIME NULL', 'SELECT 1');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @col_exists := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA='GRATLYDB' AND TABLE_NAME='PAYOUT_FINAL' AND COLUMN_NAME='DEBITED_BATCH_ID');
SET @sql := IF(@col_exists = 0, 'ALTER TABLE GRATLYDB.PAYOUT_FINAL ADD COLUMN DEBITED_BATCH_ID INT NULL', 'SELECT 1');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @col_exists := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA='GRATLYDB' AND TABLE_NAME='PAYOUT_FINAL' AND COLUMN_NAME='PAYOUT_ITEM_ID');
SET @sql := IF(@col_exists = 0, 'ALTER TABLE GRATLYDB.PAYOUT_FINAL ADD COLUMN PAYOUT_ITEM_ID INT NULL', 'SELECT 1');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @col_exists := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA='GRATLYDB' AND TABLE_NAME='PAYOUT_FINAL' AND COLUMN_NAME='PAID_AT');
SET @sql := IF(@col_exists = 0, 'ALTER TABLE GRATLYDB.PAYOUT_FINAL ADD COLUMN PAID_AT DATETIME NULL', 'SELECT 1');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @col_exists := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA='GRATLYDB' AND TABLE_NAME='PAYOUT_FINAL' AND COLUMN_NAME='DEBIT_STATUS');
SET @sql := IF(@col_exists = 0, 'ALTER TABLE GRATLYDB.PAYOUT_FINAL ADD COLUMN DEBIT_STATUS VARCHAR(32) DEFAULT \'not_debited\'', 'SELECT 1');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @col_exists := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA='GRATLYDB' AND TABLE_NAME='PAYOUT_FINAL' AND COLUMN_NAME='PAYOUT_STATUS');
SET @sql := IF(@col_exists = 0, 'ALTER TABLE GRATLYDB.PAYOUT_FINAL ADD COLUMN PAYOUT_STATUS VARCHAR(32) DEFAULT \'not_paid\'', 'SELECT 1');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

CREATE TABLE IF NOT EXISTS GRATLYDB.MOOV_ACCOUNTS (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  OWNER_TYPE ENUM('restaurant', 'employee') NOT NULL,
  OWNER_ID INT NOT NULL,
  MOOV_ACCOUNT_ID VARCHAR(255) NOT NULL,
  STATUS VARCHAR(64),
  ONBOARDING_STATUS VARCHAR(64),
  VERIFICATION_STATUS VARCHAR(64),
  VERIFICATION_UPDATED_AT DATETIME,
  LAST_CAPABILITY_CHECK DATETIME,
  CAPABILITIES_JSON JSON,
  CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY UNIQ_MOOV_ACCOUNT_OWNER (OWNER_TYPE, OWNER_ID),
  UNIQUE KEY UNIQ_MOOV_ACCOUNT_ID (MOOV_ACCOUNT_ID)
);

CREATE TABLE IF NOT EXISTS GRATLYDB.PAYMENT_METHODS (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  OWNER_TYPE ENUM('restaurant', 'employee') NOT NULL,
  OWNER_ID INT NOT NULL,
  MOOV_PAYMENT_METHOD_ID VARCHAR(255) NOT NULL,
  METHOD_TYPE VARCHAR(32) NOT NULL,
  BRAND VARCHAR(64),
  LAST4 VARCHAR(8),
  STATUS VARCHAR(32),
  IS_PREFERRED TINYINT(1) DEFAULT 0,
  IS_VERIFIED TINYINT(1) DEFAULT 0,
  CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY UNIQ_PAYMENT_METHOD (OWNER_TYPE, OWNER_ID, MOOV_PAYMENT_METHOD_ID)
);

CREATE TABLE IF NOT EXISTS GRATLYDB.TRANSFERS (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  TRANSFER_TYPE VARCHAR(32) NOT NULL,
  MOOV_TRANSFER_ID VARCHAR(255),
  STATUS VARCHAR(32) NOT NULL,
  AMOUNT_CENTS INT NOT NULL,
  CURRENCY VARCHAR(8) NOT NULL DEFAULT 'USD',
  SOURCE_ID VARCHAR(255),
  DESTINATION_ID VARCHAR(255),
  REFERENCE_TYPE VARCHAR(32),
  REFERENCE_ID INT,
  FAILURE_REASON TEXT,
  CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY UNIQ_MOOV_TRANSFER_ID (MOOV_TRANSFER_ID)
);

CREATE TABLE IF NOT EXISTS GRATLYDB.MONTHLY_FEE_CHARGES (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  RESTAURANTID INT NOT NULL,
  BILLING_PERIOD VARCHAR(16) NOT NULL,
  BILLING_DATE DATE,
  AMOUNT_CENTS INT NOT NULL,
  CURRENCY VARCHAR(8) NOT NULL DEFAULT 'USD',
  MOOV_INVOICE_ID VARCHAR(255),
  MOOV_INVOICE_STATUS VARCHAR(64),
  PAYMENT_STATUS VARCHAR(64),
  DUE_DATE DATE,
  PAID_AT DATETIME,
  FAILURE_REASON TEXT,
  NEXT_RETRY_AT DATETIME,
  CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY UNIQ_MONTHLY_FEE (RESTAURANTID, BILLING_PERIOD),
  CONSTRAINT FK_MONTHLY_FEE_RESTAURANT FOREIGN KEY(RESTAURANTID)
    REFERENCES GRATLYDB.SRC_ONBOARDING(RESTAURANTID)
);

CREATE TABLE IF NOT EXISTS GRATLYDB.BILLING_EMAILS (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  RESTAURANTID INT NOT NULL,
  CHARGE_ID INT NOT NULL,
  EMAIL_TYPE VARCHAR(32) NOT NULL,
  SENT_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY UNIQ_BILLING_EMAIL (CHARGE_ID, EMAIL_TYPE),
  CONSTRAINT FK_BILLING_EMAIL_CHARGE FOREIGN KEY(CHARGE_ID)
    REFERENCES GRATLYDB.MONTHLY_FEE_CHARGES(ID)
);

CREATE TABLE IF NOT EXISTS GRATLYDB.NIGHTLY_DEBIT_BATCHES (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  RESTAURANTID INT NOT NULL,
  BUSINESS_DATE DATE NOT NULL,
  STATUS VARCHAR(32) NOT NULL,
  PRINCIPAL_TOTAL_CENTS INT NOT NULL,
  FEE_TOTAL_CENTS INT NOT NULL,
  TOTAL_DEBIT_CENTS INT NOT NULL,
  MOOV_TRANSFER_ID VARCHAR(255),
  FAILURE_REASON TEXT,
  CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY UNIQ_NIGHTLY_BATCH (RESTAURANTID, BUSINESS_DATE),
  KEY IDX_BATCH_STATUS (STATUS, BUSINESS_DATE),
  KEY IDX_BATCH_UPDATED (UPDATED_AT),
  CONSTRAINT FK_NIGHTLY_DEBIT_RESTAURANT FOREIGN KEY(RESTAURANTID)
    REFERENCES GRATLYDB.SRC_ONBOARDING(RESTAURANTID)
);

CREATE TABLE IF NOT EXISTS GRATLYDB.PAYOUT_ITEMS (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  RESTAURANTID INT NOT NULL,
  EMPLOYEEGUID VARCHAR(36) NOT NULL,
  PAYOUT_FINAL_ID INT NOT NULL,
  GROSS_AMOUNT_CENTS INT NOT NULL,
  NET_AMOUNT_CENTS INT NOT NULL,
  FEE_AMOUNT_CENTS_SNAPSHOT INT NOT NULL,
  FEE_PAYER_SNAPSHOT VARCHAR(16) NOT NULL,
  RAIL VARCHAR(32) NOT NULL,
  STATUS VARCHAR(32) NOT NULL,
  MOOV_TRANSFER_ID VARCHAR(255),
  PAID_AT DATETIME,
  FAILURE_REASON TEXT,
  CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY UNIQ_PAYOUT_ITEM_FINAL (PAYOUT_FINAL_ID),
  CONSTRAINT FK_PAYOUT_ITEM_FINAL FOREIGN KEY(PAYOUT_FINAL_ID)
    REFERENCES GRATLYDB.PAYOUT_FINAL(PAYOUT_FINALID)
);

CREATE TABLE IF NOT EXISTS GRATLYDB.LEDGER_ENTRIES (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  RESTAURANTID INT,
  ENTRY_TYPE VARCHAR(32) NOT NULL,
  AMOUNT_CENTS INT NOT NULL,
  CURRENCY VARCHAR(8) NOT NULL DEFAULT 'USD',
  REFERENCE_TYPE VARCHAR(32),
  REFERENCE_ID INT,
  CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
  INDEX IDX_LEDGER_RESTAURANT (RESTAURANTID)
);

CREATE TABLE IF NOT EXISTS GRATLYDB.WEBHOOK_EVENTS (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  PROVIDER VARCHAR(32) NOT NULL,
  EVENT_ID VARCHAR(255) NOT NULL,
  EVENT_TYPE VARCHAR(255) NOT NULL,
  PAYLOAD_JSON JSON,
  PAYLOAD_HASH VARCHAR(64),
  RECEIVED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
  PROCESSED_AT DATETIME NULL,
  PROCESSING_ERROR TEXT,
  UNIQUE KEY UNIQ_WEBHOOK_EVENT (PROVIDER, EVENT_ID),
  KEY IDX_PAYLOAD_HASH (PROVIDER, PAYLOAD_HASH),
  KEY IDX_PROVIDER_TIME (PROVIDER, RECEIVED_AT)
);

CREATE TABLE IF NOT EXISTS GRATLYDB.IDEMPOTENCY_KEYS (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  SCOPE VARCHAR(64) NOT NULL,
  IDEMPOTENCY_KEY VARCHAR(255) NOT NULL,
  STATUS VARCHAR(32) NOT NULL,
  LOCKED_AT DATETIME NOT NULL,
  COMPLETED_AT DATETIME NULL,
  RESULT_JSON JSON,
  ERROR_TEXT TEXT,
  UNIQUE KEY UNIQ_IDEMPOTENCY (SCOPE, IDEMPOTENCY_KEY)
);

-- Add indexes for Moov v2025.07.00 verification status queries
SET @idx_exists := (SELECT COUNT(*) FROM information_schema.STATISTICS WHERE TABLE_SCHEMA='GRATLYDB' AND TABLE_NAME='PAYOUT_FINAL' AND INDEX_NAME='IDX_PAYOUT_STATUS');
SET @sql := IF(@idx_exists = 0, 'ALTER TABLE GRATLYDB.PAYOUT_FINAL ADD INDEX IDX_PAYOUT_STATUS (PAYOUT_STATUS, UPDATED_AT)', 'SELECT 1');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

-- Ensure PAYOUT_STATUS column exists on PAYOUT_FINAL
SET @col_exists := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA='GRATLYDB' AND TABLE_NAME='PAYOUT_FINAL' AND COLUMN_NAME='PAYOUT_STATUS');
SET @sql := IF(@col_exists = 0, 'ALTER TABLE GRATLYDB.PAYOUT_FINAL ADD COLUMN PAYOUT_STATUS VARCHAR(32)', 'SELECT 1');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

-- Ensure FAILURE_REASON column exists on PAYOUT_FINAL
SET @col_exists := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA='GRATLYDB' AND TABLE_NAME='PAYOUT_FINAL' AND COLUMN_NAME='FAILURE_REASON');
SET @sql := IF(@col_exists = 0, 'ALTER TABLE GRATLYDB.PAYOUT_FINAL ADD COLUMN FAILURE_REASON TEXT', 'SELECT 1');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

-- Ensure DEBITED_BATCH_ID column exists on PAYOUT_FINAL
SET @col_exists := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA='GRATLYDB' AND TABLE_NAME='PAYOUT_FINAL' AND COLUMN_NAME='DEBITED_BATCH_ID');
SET @sql := IF(@col_exists = 0, 'ALTER TABLE GRATLYDB.PAYOUT_FINAL ADD COLUMN DEBITED_BATCH_ID INT', 'SELECT 1');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

-- Ensure DEBIT_STATUS column exists on PAYOUT_FINAL
SET @col_exists := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA='GRATLYDB' AND TABLE_NAME='PAYOUT_FINAL' AND COLUMN_NAME='DEBIT_STATUS');
SET @sql := IF(@col_exists = 0, 'ALTER TABLE GRATLYDB.PAYOUT_FINAL ADD COLUMN DEBIT_STATUS VARCHAR(32)', 'SELECT 1');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

-- Ensure APPROVED_AT column exists on PAYOUT_FINAL
SET @col_exists := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA='GRATLYDB' AND TABLE_NAME='PAYOUT_FINAL' AND COLUMN_NAME='APPROVED_AT');
SET @sql := IF(@col_exists = 0, 'ALTER TABLE GRATLYDB.PAYOUT_FINAL ADD COLUMN APPROVED_AT DATETIME', 'SELECT 1');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

-- Ensure PAYOUT_ITEM_ID column exists on PAYOUT_FINAL
SET @col_exists := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA='GRATLYDB' AND TABLE_NAME='PAYOUT_FINAL' AND COLUMN_NAME='PAYOUT_ITEM_ID');
SET @sql := IF(@col_exists = 0, 'ALTER TABLE GRATLYDB.PAYOUT_FINAL ADD COLUMN PAYOUT_ITEM_ID INT', 'SELECT 1');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

-- Ensure USERSLUG column exists on USER_MASTER for unified URL routing
SET @col_exists := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA='GRATLYDB' AND TABLE_NAME='USER_MASTER' AND COLUMN_NAME='USERSLUG');
SET @sql := IF(@col_exists = 0, 'ALTER TABLE GRATLYDB.USER_MASTER ADD COLUMN USERSLUG VARCHAR(32) UNIQUE', 'SELECT 1');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

-- Create unique index on USERSLUG for fast lookups
SET @idx_exists := (SELECT COUNT(*) FROM information_schema.STATISTICS WHERE TABLE_SCHEMA='GRATLYDB' AND TABLE_NAME='USER_MASTER' AND INDEX_NAME='IDX_USERSLUG');
SET @sql := IF(@idx_exists = 0, 'CREATE UNIQUE INDEX IDX_USERSLUG ON GRATLYDB.USER_MASTER(USERSLUG)', 'SELECT 1');
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;
