
-- This syntax will create the new DB

  CREATE DATABASE IF NOT EXISTS GRATLYDB;


-- This table is the first table created after customer is onboarded

  CREATE TABLE IF NOT EXISTS GRATLYDB.SRC_ONBOARDING (
         RESTAURANTID INT AUTO_INCREMENT PRIMARY KEY,
         RESTAURANTGUID VARCHAR(36) NOT NULL,
         SECRETKEY VARCHAR(64) NOT NULL,
         CLIENTSECRET VARCHAR(128) NOT NULL,
         USERACCESSTYPE VARCHAR(64) NOT NULL
     );

ALTER TABLE GRATLYDB.SRC_ONBOARDING AUTO_INCREMENT = 100;

-- INSERT INTO GRATLYDB.SRC_ONBOARDING(RESTAURANTGUID ,SECRETKEY, CLIENTSECRET, USERACCESSTYPE) values('0169bd32-becf-4b04-9093-d7d4db1dc242','WZ8mobWCpK4AcXQjDHgZcgQIMOCaQ3xs','XsplfAXitqH1ePen0nkEWV_lFuCEaabjEPhpagi_zLlKxDVdIrPdwhWJgj0W2o2v','TOAST_MACHINE_CLIENT');

-- This script will store the details of the restaurant(s) and is a source table

  CREATE TABLE IF NOT EXISTS GRATLYDB.SRC_RESTAURANTDETAILS(
        RESTAURANTGUID VARCHAR(36) PRIMARY KEY,
        RESTAURANTNAME VARCHAR(128) NOT NULL,
        LOCATIONNAME VARCHAR(128),
        LOCATIONCODE VARCHAR(64),
        DESCRIPTION VARCHAR(128),
        TIMEZONE VARCHAR(128),
        CURRENCYCODE VARCHAR(32),
        FIRSTBUSINESSDATE VARCHAR(16),
        ARCHIVED VARCHAR(8),
        ADDRESS1 VARCHAR(256),
        ADDRESS2 VARCHAR(256),
        CITY VARCHAR(32),
        STATECODE VARCHAR(16),
        ZIPCODE VARCHAR(8),
        COUNTRY VARCHAR(32),
        PHONE VARCHAR(16),
        WEBSITE VARCHAR(512),
        ORDERONLINE VARCHAR(512)
  );

-- This script will store the details of all employees for all restaurants and is a source table

  CREATE TABLE IF NOT EXISTS GRATLYDB.SRC_EMPLOYEES (
        RESTAURANTGUID VARCHAR(36) ,
        EMPLOYEEGUID VARCHAR(36) NOT NULL UNIQUE,
        EMPLOYEEFNAME VARCHAR(64),
        EMPLOYEELNAME VARCHAR(64),
        CHOSENNAME VARCHAR(64),
        PHONENUMBER VARCHAR(16),
        EMAIL VARCHAR(64),
        DELETED VARCHAR(8),
        DELETEDDATE DATE,
        PRIMARY KEY (RESTAURANTGUID, EMPLOYEEGUID),
        CONSTRAINT FK_RESGUIDEMP FOREIGN KEY(RESTAURANTGUID) REFERENCES  
        GRATLYDB.SRC_RESTAURANTDETAILS(RESTAURANTGUID)

  );
-- This table stores all different type of jobs for all the restaurants and is a source table

  CREATE TABLE IF NOT EXISTS GRATLYDB.SRC_JOBS (
        RESTAURANTGUID VARCHAR(36),
        JOBGUID VARCHAR(36) NOT NULL UNIQUE,
        JOBTITLE VARCHAR(64),
        ENTITYTYPE VARCHAR(32),
        CREATEDDATE DATE,
        DELETED VARCHAR(8),
        DELETEDDATE DATE,
        CODE VARCHAR(36),
        TIPPED VARCHAR(8),
        DEFAULTWAGE VARCHAR(32),
        WAGEFREQUENCY VARCHAR(32),
        PRIMARY KEY (RESTAURANTGUID,JOBGUID),
        CONSTRAINT FK_RESGUIDJOB FOREIGN KEY(RESTAURANTGUID) REFERENCES  
        GRATLYDB.SRC_RESTAURANTDETAILS(RESTAURANTGUID)
  );


-- This table stores all roles assigned to an employee by the Restaurant and is a source table

  CREATE TABLE IF NOT EXISTS GRATLYDB.SRC_EMPLOYEEROLE (
        RESTAURANTGUID VARCHAR(36),
        EMPLOYEEGUID VARCHAR(36),
        NAME VARCHAR(64),
        JOBGUID varchar(36),
        PRIMARY KEY(RESTAURANTGUID,EMPLOYEEGUID,JOBGUID),
        CONSTRAINT FK_RESGUIDEMPR FOREIGN KEY(RESTAURANTGUID) REFERENCES  
        GRATLYDB.SRC_RESTAURANTDETAILS(RESTAURANTGUID),
        CONSTRAINT FK_EMPGUID FOREIGN KEY(EMPLOYEEGUID) REFERENCES  
        GRATLYDB.SRC_EMPLOYEES(EMPLOYEEGUID),
        CONSTRAINT FK_JOBGUID FOREIGN KEY(JOBGUID) REFERENCES  
        GRATLYDB.SRC_JOBS(JOBGUID)
  );

-- This script stores all tables in the restaurant and is a source table

  CREATE TABLE IF NOT EXISTS GRATLYDB.SRC_TABLES (
     RESTAURANTGUID VARCHAR(36),		
     TABLEGUID VARCHAR(36),
     ENTITYTYPE VARCHAR(16),
     TABLENAME VARCHAR(32),
     PRIMARY KEY(RESTAURANTGUID,TABLEGUID),
     CONSTRAINT FK_RESGUIDTAB FOREIGN KEY(RESTAURANTGUID) REFERENCES  
     GRATLYDB.SRC_RESTAURANTDETAILS(RESTAURANTGUID)
  );

-- This table get all time entries for all employees for the current day and is a source table

  CREATE TABLE IF NOT EXISTS GRATLYDB.SRC_TIMEENTRIES (
    RESTAURANTGUID VARCHAR(36),		
    TIMEENTRYGUID VARCHAR(36),
    ENTITYTYPE VARCHAR(50) NOT NULL,
    EXTERNALID VARCHAR(255),
    EMPLOYEEGUID VARCHAR(36),
    JOBID VARCHAR(36),
    SHIFTREFERENCE VARCHAR(36),
    INDATE VARCHAR(36),
    OUTDATE VARCHAR(36),
    BUSINESSDATE VARCHAR(12),
    REGULARHOURS DECIMAL(5,2) DEFAULT 0.00,
    OVERTIMEHOURS DECIMAL(5,2) DEFAULT 0.00,
    HOURLYWAGE DECIMAL(7,2),
    TIPSWITHHELD DECIMAL(7,2) DEFAULT 0.00,
    NONCASHSALES DECIMAL(10,2) DEFAULT 0.00,
    CASHSALES DECIMAL(10,2) DEFAULT 0.00,
    NONCASHGRATUITYSERVICECHARGES DECIMAL(10,2) DEFAULT 0.00,
    CASHGRATUITYSERVICECHARGES DECIMAL(10,2) DEFAULT 0.00,
    NONCASHTIPS DECIMAL(5,2),
    DECLAREDCASHTIPS DECIMAL(10,2),
    AUTOCLOCKEDOUT BOOLEAN DEFAULT FALSE,
    DELETED BOOLEAN DEFAULT FALSE,
    CREATEDDATE VARCHAR(36),
    MODIFIEDDATE VARCHAR(36),
    DELETEDDATE VARCHAR(36),
    PRIMARY KEY (RESTAURANTGUID,TIMEENTRYGUID),
    CONSTRAINT FK_RESGUIDTME FOREIGN KEY(RESTAURANTGUID) REFERENCES  
    GRATLYDB.SRC_RESTAURANTDETAILS(RESTAURANTGUID),
    CONSTRAINT FK_EMPGUIDTME FOREIGN KEY(EMPLOYEEGUID) REFERENCES  
    GRATLYDB.SRC_EMPLOYEES(EMPLOYEEGUID)
  );

-- This table contains all orders for current day for all restaurants and is a source table

  CREATE TABLE IF NOT EXISTS GRATLYDB.SRC_ALLORDERS (
    RESTAURANTGUID VARCHAR(36),
    ORDERGUID VARCHAR(36),
    DISPLAYNUMBER INT,
    BUSINESSDATE VARCHAR(12),
    ORDERSOURCE VARCHAR(64),
    TABLEGUID VARCHAR(36),
    ORDERPAIDDATE VARCHAR(36),
    VOIDED VARCHAR(8),
    OPENEDDATE VARCHAR(36),
    PREPTIME VARCHAR(32),
    PAYMENTTYPE VARCHAR(16),
    REFUNDSTATUS VARCHAR(16),
    PAYMENTSTATUS VARCHAR(16),
    NETAMOUNT DECIMAL(7,2),
    TIPAMOUNT DECIMAL(5,2),
    GRATUITYAMOUNT DECIMAL(5,2),
    TAXAMOUNT DECIMAL(7,2),
    TOTALAMOUNT DECIMAL(7,2),
    EMPLOYEEGUID VARCHAR(36),
    NUMBEROFGUESTS INT,
    DURATION BIGINT,
    APPROVALSTATUS VARCHAR(16),
    PRIMARY KEY (RESTAURANTGUID,ORDERGUID),
    CONSTRAINT FK_RESGUIDALO FOREIGN KEY(RESTAURANTGUID) REFERENCES  
    GRATLYDB.SRC_RESTAURANTDETAILS(RESTAURANTGUID),
    CONSTRAINT FK_EMPGUIDALO FOREIGN KEY(EMPLOYEEGUID) REFERENCES  
    GRATLYDB.SRC_EMPLOYEES(EMPLOYEEGUID)
  ); 

-- This Table stores user info from signup page for application and is a master table

  CREATE TABLE IF NOT EXISTS GRATLYDB.USER_MASTER (
    USERID INT AUTO_INCREMENT PRIMARY KEY,
    FIRSTNAME VARCHAR(32) NOT NULL,
    LASTNAME VARCHAR(32) NOT NULL,
    EMAIL VARCHAR(64) NOT NULL UNIQUE,
    PHONENUMBER VARCHAR(32),
    PASSWORD_HASH VARCHAR(255) NOT NULL,
    USERSTATUS BOOLEAN,
    CREATEDAT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    USERSTATUS TINYINT(1) DEFAULT NULL
  );

-- This Table stores the association of the user to restaurant for all users 

  CREATE TABLE IF NOT EXISTS GRATLYDB.USERRESTAURANT (
   USERRESTAURANTID INT AUTO_INCREMENT PRIMARY KEY,
   USERID INT,
   RESTAURANTID INT,
   CONSTRAINT FK_RESID FOREIGN KEY(RESTAURANTID) REFERENCES  
   GRATLYDB.SRC_ONBOARDING(RESTAURANTID),
   CONSTRAINT FK_USERID FOREIGN KEY(USERID) REFERENCES  
   GRATLYDB.USER_MASTER(USERID)
  );

CREATE TABLE GRATLYDB.MSTR_PERMISSIONS (
  PERMISSIONSID INT NOT NULL AUTO_INCREMENT,
  PERMISSIONSNAME VARCHAR(128) DEFAULT NULL,
  DELETED TINYINT(1) DEFAULT NULL,
  DISPLAY TINYINT(1) DEFAULT 1,
  CREATEDDATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  MODIFIEDDATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (PERMISSIONSID)
);

INSERT INTO GRATLYDB.MSTR_PERMISSIONS(PERMISSIONSNAME,DELETED,DISPLAY) VALUES ('Create Payout Schedules',0,1);
INSERT INTO GRATLYDB.MSTR_PERMISSIONS(PERMISSIONSNAME,DELETED,DISPLAY) VALUES ('Approve Payouts',0,1);
INSERT INTO GRATLYDB.MSTR_PERMISSIONS(PERMISSIONSNAME,DELETED,DISPLAY) VALUES ('Manage Team',0,1);
INSERT INTO GRATLYDB.MSTR_PERMISSIONS(PERMISSIONSNAME,DELETED,DISPLAY) VALUES ('Admin Access',0,1);
INSERT INTO GRATLYDB.MSTR_PERMISSIONS(PERMISSIONSNAME,DELETED,DISPLAY) VALUES ('Superadmin Access',0,0);
INSERT INTO GRATLYDB.MSTR_PERMISSIONS(PERMISSIONSNAME,DELETED,DISPLAY) VALUES ('Employee Only',0,1);
INSERT INTO GRATLYDB.MSTR_PERMISSIONS(PERMISSIONSNAME,DELETED,DISPLAY) VALUES ('Manager Access',0,1);
INSERT INTO GRATLYDB.MSTR_PERMISSIONS(PERMISSIONSNAME,DELETED,DISPLAY) VALUES ('Report for Payroll',0,1);

ALTER TABLE GRATLYDB.MSTR_PERMISSIONS
  ADD COLUMN IF NOT EXISTS DISPLAY TINYINT(1) DEFAULT 1;

UPDATE GRATLYDB.MSTR_PERMISSIONS
SET DISPLAY = 1
WHERE DISPLAY IS NULL;

UPDATE GRATLYDB.MSTR_PERMISSIONS
SET DISPLAY = 0
WHERE PERMISSIONSNAME = 'Superadmin Access';

-- This Table stores the permissions for all users

CREATE TABLE IF NOT EXISTS GRATLYDB.USER_PERMISSIONS(
  USERPERMISSIONSID INT AUTO_INCREMENT PRIMARY KEY, 
  USERID INT,
  PERMISSIONSID INT,
  CREATEDDATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  MODIFIEDDATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT FK_USERID_UP FOREIGN KEY(USERID) REFERENCES  
    GRATLYDB.USER_MASTER(USERID),
  CONSTRAINT FK_PERMISSIONSID_UP FOREIGN KEY(PERMISSIONSID) REFERENCES  
    GRATLYDB.MSTR_PERMISSIONS(PERMISSIONSID)
);

-- Below tables will store ALL values for Payout Schedule created for each restaurant

CREATE TABLE IF NOT EXISTS GRATLYDB.PAYOUT_SCHEDULE (
PAYOUT_SCHEDULEID INT AUTO_INCREMENT PRIMARY KEY,
RESTAURANTID INT NOT NULL,
USERID INT NOT NULL,
NAME VARCHAR(128) NOT NULL,
START_DAY VARCHAR(8),
END_DAY VARCHAR(8),
START_TIME VARCHAR(8),
END_TIME VARCHAR(8),
PAYOUTTRIGGER_GRATUITY FLOAT,
PAYOUTTRIGGER_TIPS FLOAT,
PAYOUT_RULE_ID VARCHAR(64) NOT NULL, -- 1 - CUSTOM PAYOUT, 2 - EQUAL PAYOUT, 3 - HOUR BASED PAYOUT, 4 - JOB WEIGHTED PAYOUT
PREPAYOUT_FLAG BOOLEAN,              -- 1 - VALUE EXISTS FOR PRE_PAYOUT, 0 - NO VALUE FOR PREPAYOUT
CREATEDDATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
MODIFIEDDATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
CONSTRAINT FK_PAYOUT_RESTAURANTID FOREIGN KEY(RESTAURANTID) REFERENCES GRATLYDB.SRC_ONBOARDING(RESTAURANTID),
CONSTRAINT FK_PAYOUT_USERID FOREIGN KEY(USERID) REFERENCES GRATLYDB.USER_MASTER(USERID)
);



CREATE TABLE IF NOT EXISTS GRATLYDB.PAYOUTRECEIVERS (
PAYOUTRECEIVERSID INT AUTO_INCREMENT PRIMARY KEY,
PAYOUT_SCHEDULEID INT,
PAYOUT_RULE_ID VARCHAR(64),
CONTRIBUTOR_RECIEVER BOOLEAN,
PAYOUT_RECEIVERID VARCHAR(36),
PAYOUT_PERCENTAGE FLOAT,
CREATEDDATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
MODIFIEDDATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
CONSTRAINT FK_PAYOUT_SCHEDULEID FOREIGN KEY(PAYOUT_SCHEDULEID) REFERENCES GRATLYDB.PAYOUT_SCHEDULE(PAYOUT_SCHEDULEID)
);


CREATE TABLE IF NOT EXISTS GRATLYDB.PAYOUT_CUSTOM (
PAYOUT_CUSTOMID  INT AUTO_INCREMENT PRIMARY KEY,
PAYOUT_SCHEDULEID INT,
INDIVIDUAL_PAYOUT FLOAT,
GROUPCONTRIBUTION FLOAT,
CREATEDDATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
MODIFIEDDATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
CONSTRAINT FK_PAYOUT_SCHEDULEID_PC FOREIGN KEY(PAYOUT_SCHEDULEID) REFERENCES GRATLYDB.PAYOUT_SCHEDULE(PAYOUT_SCHEDULEID)
);

CREATE TABLE IF NOT EXISTS GRATLYDB.PREPAYOUT (
PREPAYOUTID INT AUTO_INCREMENT PRIMARY KEY,
PAYOUT_SCHEDULEID INT,
PREPAYOUTOPTION BOOLEAN, -- 0 MEANS PERCENTAGE AND 1 MEANS FIXED AMOUNT
PREPAYOUT_VALUE FLOAT,
USERACCOUNT VARCHAR(36),
CREATEDDATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
MODIFIEDDATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
CONSTRAINT FK_PAYOUT_SCHEDULEID_PP FOREIGN KEY(PAYOUT_SCHEDULEID) REFERENCES GRATLYDB.PAYOUT_SCHEDULE(PAYOUT_SCHEDULEID)
);

CREATE TABLE IF NOT EXISTS GRATLYDB.EMAIL_INVITES (
INVITEID INT AUTO_INCREMENT PRIMARY KEY,
USERID INT NOT NULL,
EMPLOYEEGUID VARCHAR(64),
EMAIL VARCHAR(128) NOT NULL,
FIRSTNAME VARCHAR(64),
LASTNAME VARCHAR(64),
STATUS VARCHAR(32) NOT NULL,
PROVIDER VARCHAR(32),
PROVIDER_RESPONSE TEXT,
CREATEDDATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
MODIFIEDDATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
INDEX IDX_EMAIL_INVITES_USERID (USERID),
INDEX IDX_EMAIL_INVITES_EMAIL (EMAIL),
CONSTRAINT FK_EMAIL_INVITES_USERID FOREIGN KEY(USERID) REFERENCES GRATLYDB.USER_MASTER(USERID)
);

CREATE TABLE IF NOT EXISTS GRATLYDB.PAYOUT_APPROVAL (
PAYOUT_APPROVALID INT AUTO_INCREMENT PRIMARY KEY,
RESTAURANTID INT NOT NULL,
PAYOUT_SCHEDULEID INT NOT NULL,
BUSINESSDATE VARCHAR(32) NOT NULL,
IS_APPROVED TINYINT(1) NOT NULL DEFAULT 0,
UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
UNIQUE KEY uq_payout_approval (RESTAURANTID, PAYOUT_SCHEDULEID, BUSINESSDATE)
);

CREATE TABLE IF NOT EXISTS GRATLYDB.PAYOUT_APPROVAL_ITEMS (
PAYOUT_APPROVAL_ITEMID INT AUTO_INCREMENT PRIMARY KEY,
PAYOUT_APPROVALID INT NOT NULL,
RESTAURANTID INT NOT NULL,
PAYOUT_SCHEDULEID INT NOT NULL,
BUSINESSDATE VARCHAR(32) NOT NULL,
EMPLOYEEGUID VARCHAR(36),
EMPLOYEE_NAME VARCHAR(128),
JOBTITLE VARCHAR(128),
IS_CONTRIBUTOR VARCHAR(8),
PAYOUT_RECEIVER_ID VARCHAR(128),
PAYOUT_PERCENTAGE DECIMAL(10,2),
TOTAL_SALES DECIMAL(12,2),
NET_SALES DECIMAL(12,2),
TOTAL_TIPS DECIMAL(12,2),
TOTAL_GRATUITY DECIMAL(12,2),
OVERALL_TIPS DECIMAL(12,2),
OVERALL_GRATUITY DECIMAL(12,2),
PAYOUT_TIPS DECIMAL(12,2),
PAYOUT_GRATUITY DECIMAL(12,2),
NET_PAYOUT DECIMAL(12,2),
UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
UNIQUE KEY UQ_PAYOUT_APPROVAL_ITEM (PAYOUT_APPROVALID, EMPLOYEEGUID, JOBTITLE, IS_CONTRIBUTOR),
CONSTRAINT FK_PAYOUT_APPROVAL_ITEM FOREIGN KEY(PAYOUT_APPROVALID)
REFERENCES GRATLYDB.PAYOUT_APPROVAL(PAYOUT_APPROVALID)
ON DELETE CASCADE
);

-- This script store the final approved Payout Schedule details

CREATE TABLE IF NOT EXISTS GRATLYDB.PAYOUT_FINAL (
PAYOUT_FINALID INT AUTO_INCREMENT PRIMARY KEY,
PAYOUT_APPROVALID INT NOT NULL,
RESTAURANTID INT NOT NULL,
PAYOUT_SCHEDULEID INT NOT NULL,
BUSINESSDATE VARCHAR(32) NOT NULL,
EMPLOYEEGUID VARCHAR(36),
EMPLOYEE_NAME VARCHAR(128),
JOBTITLE VARCHAR(128),
IS_CONTRIBUTOR VARCHAR(8),
PAYOUT_RECEIVER_ID VARCHAR(128),
PAYOUT_PERCENTAGE DECIMAL(10,2),
TOTAL_SALES DECIMAL(12,2),
NET_SALES DECIMAL(12,2),
TOTAL_TIPS DECIMAL(12,2),
TOTAL_GRATUITY DECIMAL(12,2),
OVERALL_TIPS DECIMAL(12,2),
OVERALL_GRATUITY DECIMAL(12,2),
PAYOUT_TIPS DECIMAL(12,2),
PAYOUT_GRATUITY DECIMAL(12,2),
NET_PAYOUT DECIMAL(12,2),
PREPAYOUT_DEDUCTION DECIMAL(12,2),
APPROVED_USERID INT NOT NULL,
UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
UNIQUE KEY UQ_PAYOUT_FINAL (PAYOUT_APPROVALID, EMPLOYEEGUID, JOBTITLE, IS_CONTRIBUTOR),
CONSTRAINT FK_PAYOUT_FINAL FOREIGN KEY(PAYOUT_APPROVALID) REFERENCES GRATLYDB.PAYOUT_APPROVAL(PAYOUT_APPROVALID));

-- Stripe connected accounts for employee payouts
CREATE TABLE IF NOT EXISTS GRATLYDB.STRIPE_CONNECTED_ACCOUNTS (
  RESTAURANTGUID VARCHAR(36),
  EMPLOYEEGUID VARCHAR(64) NOT NULL PRIMARY KEY,
  STRIPE_ACCOUNT_ID VARCHAR(64) NOT NULL,
  CHARGES_ENABLED TINYINT(1) DEFAULT 0,
  PAYOUTS_ENABLED TINYINT(1) DEFAULT 0,
  DETAILS_SUBMITTED TINYINT(1) DEFAULT 0,
  DISABLED_REASON VARCHAR(255),
  ACCOUNT_DEAUTHORIZED TINYINT(1) DEFAULT 0,
  CREATEDAT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UPDATEDAT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Stripe payment intent events (for notifications)
CREATE TABLE IF NOT EXISTS GRATLYDB.STRIPE_PAYMENT_EVENTS (
  RESTAURANTGUID VARCHAR(36),
  EVENT_ID VARCHAR(255) NOT NULL PRIMARY KEY,
  EVENT_TYPE VARCHAR(128) NOT NULL,
  PAYMENT_INTENT_ID VARCHAR(255),
  EMPLOYEEGUID VARCHAR(64),
  AMOUNT BIGINT,
  CURRENCY VARCHAR(16),
  STATUS VARCHAR(64),
  CREATED_AT DATETIME,
  RAW_PAYLOAD JSON
);

-- Stripe dispute events (ACH/card disputes)
CREATE TABLE IF NOT EXISTS GRATLYDB.STRIPE_DISPUTE_EVENTS (
  RESTAURANTGUID VARCHAR(36),
  EVENT_ID VARCHAR(255) NOT NULL PRIMARY KEY,
  EVENT_TYPE VARCHAR(128) NOT NULL,
  DISPUTE_ID VARCHAR(255),
  CHARGE_ID VARCHAR(255),
  EMPLOYEEGUID VARCHAR(64),
  AMOUNT BIGINT,
  CURRENCY VARCHAR(16),
  STATUS VARCHAR(64),
  REASON VARCHAR(255),
  CREATED_AT DATETIME,
  RAW_PAYLOAD JSON
);

-- Stripe balance availability events
CREATE TABLE IF NOT EXISTS GRATLYDB.STRIPE_BALANCE_EVENTS (
  RESTAURANTGUID VARCHAR(36),
  EVENT_ID VARCHAR(255) NOT NULL PRIMARY KEY,
  EVENT_TYPE VARCHAR(128) NOT NULL,
  CREATED_AT DATETIME,
  RAW_PAYLOAD JSON
);

-- Stripe transfers (platform -> connected account)
CREATE TABLE IF NOT EXISTS GRATLYDB.STRIPE_TRANSFER_EVENTS (
  RESTAURANTGUID VARCHAR(36),
  EVENT_ID VARCHAR(255) NOT NULL PRIMARY KEY,
  EVENT_TYPE VARCHAR(128) NOT NULL,
  TRANSFER_ID VARCHAR(255),
  EMPLOYEEGUID VARCHAR(64),
  AMOUNT BIGINT,
  CURRENCY VARCHAR(16),
  STATUS VARCHAR(64),
  DESTINATION_ACCOUNT VARCHAR(255),
  CREATED_AT DATETIME,
  RAW_PAYLOAD JSON
);

-- Stripe payouts (connected account -> employee bank)
CREATE TABLE IF NOT EXISTS GRATLYDB.STRIPE_PAYOUT_EVENTS (
  RESTAURANTGUID VARCHAR(36),
  EVENT_ID VARCHAR(255) NOT NULL PRIMARY KEY,
  EVENT_TYPE VARCHAR(128) NOT NULL,
  PAYOUT_ID VARCHAR(255),
  EMPLOYEEGUID VARCHAR(64),
  AMOUNT BIGINT,
  CURRENCY VARCHAR(16),
  STATUS VARCHAR(64),
  ARRIVAL_DATE BIGINT,
  PAYOUT_METHOD VARCHAR(32),
  DESTINATION VARCHAR(255),
  ACCOUNT_ID VARCHAR(255),
  CREATED_AT DATETIME,
  RAW_PAYLOAD JSON
);

-- Stripe restaurant settings (ACH debits)
CREATE TABLE IF NOT EXISTS GRATLYDB.STRIPE_RESTAURANT_SETTINGS (
  RESTAURANTGUID VARCHAR(36),
  RESTAURANTID INT NOT NULL PRIMARY KEY,
  STRIPE_CUSTOMER_ID VARCHAR(255),
  US_BANK_PAYMENT_METHOD_ID VARCHAR(255),
  BANK_LAST4 VARCHAR(8),
  BANK_NAME VARCHAR(255),
  UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
    ON UPDATE CURRENT_TIMESTAMP
);

-- Restaurant payment routing (one-time choice)
CREATE TABLE IF NOT EXISTS GRATLYDB.RESTAURANT_PAYMENT_ROUTING (
  RESTAURANTGUID VARCHAR(36),
  RESTAURANTID INT NOT NULL PRIMARY KEY,
  PROVIDER VARCHAR(16) NOT NULL DEFAULT 'stripe',
  UPDATED_BY_USERID INT,
  UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
    ON UPDATE CURRENT_TIMESTAMP
);

-- Stripe employee carry-forward (net < fee)
CREATE TABLE IF NOT EXISTS GRATLYDB.STRIPE_EMPLOYEE_CARRY_FORWARD (
  RESTAURANTGUID VARCHAR(36),
  EMPLOYEEGUID VARCHAR(64) NOT NULL,
  RESTAURANTID INT NOT NULL,
  CARRY_FORWARD_CENTS BIGINT NOT NULL DEFAULT 0,
  UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
    ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (EMPLOYEEGUID, RESTAURANTID)
);

-- Stripe settlement transfers (idempotency per employee)
CREATE TABLE IF NOT EXISTS GRATLYDB.STRIPE_SETTLEMENT_TRANSFERS (
  RESTAURANTGUID VARCHAR(36),
  SETTLEMENT_ID VARCHAR(64) NOT NULL,
  EMPLOYEEGUID VARCHAR(64) NOT NULL,
  TRANSFER_ID VARCHAR(255) NOT NULL,
  AMOUNT_CENTS BIGINT NOT NULL,
  FEE_CENTS BIGINT NOT NULL,
  CARRY_FORWARD_CENTS BIGINT NOT NULL DEFAULT 0,
  CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (SETTLEMENT_ID, EMPLOYEEGUID)
);

CREATE INDEX IDX_STRIPE_SETTLEMENT_TRANSFER_ID
  ON GRATLYDB.STRIPE_SETTLEMENT_TRANSFERS (TRANSFER_ID);

-- Indexes for Stripe event tables
CREATE INDEX IDX_STRIPE_PAYMENT_EMPLOYEE ON GRATLYDB.STRIPE_PAYMENT_EVENTS (EMPLOYEEGUID);
CREATE INDEX IDX_STRIPE_PAYMENT_RESTAURANT ON GRATLYDB.STRIPE_PAYMENT_EVENTS (RESTAURANTGUID);
CREATE INDEX IDX_STRIPE_PAYMENT_INTENT ON GRATLYDB.STRIPE_PAYMENT_EVENTS (PAYMENT_INTENT_ID);

CREATE INDEX IDX_STRIPE_DISPUTE_EMPLOYEE ON GRATLYDB.STRIPE_DISPUTE_EVENTS (EMPLOYEEGUID);
CREATE INDEX IDX_STRIPE_DISPUTE_RESTAURANT ON GRATLYDB.STRIPE_DISPUTE_EVENTS (RESTAURANTGUID);
CREATE INDEX IDX_STRIPE_DISPUTE_CHARGE ON GRATLYDB.STRIPE_DISPUTE_EVENTS (CHARGE_ID);

CREATE INDEX IDX_STRIPE_BALANCE_CREATED ON GRATLYDB.STRIPE_BALANCE_EVENTS (CREATED_AT);

CREATE INDEX IDX_STRIPE_TRANSFER_EMPLOYEE ON GRATLYDB.STRIPE_TRANSFER_EVENTS (EMPLOYEEGUID);
CREATE INDEX IDX_STRIPE_TRANSFER_RESTAURANT ON GRATLYDB.STRIPE_TRANSFER_EVENTS (RESTAURANTGUID);
CREATE INDEX IDX_STRIPE_TRANSFER_ID ON GRATLYDB.STRIPE_TRANSFER_EVENTS (TRANSFER_ID);

CREATE INDEX IDX_STRIPE_PAYOUT_EMPLOYEE ON GRATLYDB.STRIPE_PAYOUT_EVENTS (EMPLOYEEGUID);
CREATE INDEX IDX_STRIPE_PAYOUT_RESTAURANT ON GRATLYDB.STRIPE_PAYOUT_EVENTS (RESTAURANTGUID);
CREATE INDEX IDX_STRIPE_PAYOUT_ID ON GRATLYDB.STRIPE_PAYOUT_EVENTS (PAYOUT_ID);

-- Optional: move RESTAURANTGUID to the first column on existing tables
ALTER TABLE GRATLYDB.STRIPE_BALANCE_EVENTS
  MODIFY COLUMN RESTAURANTGUID VARCHAR(36) FIRST;
ALTER TABLE GRATLYDB.STRIPE_CONNECTED_ACCOUNTS
  MODIFY COLUMN RESTAURANTGUID VARCHAR(36) FIRST;
ALTER TABLE GRATLYDB.STRIPE_DISPUTE_EVENTS
  MODIFY COLUMN RESTAURANTGUID VARCHAR(36) FIRST;
ALTER TABLE GRATLYDB.STRIPE_EMPLOYEE_CARRY_FORWARD
  MODIFY COLUMN RESTAURANTGUID VARCHAR(36) FIRST;
ALTER TABLE GRATLYDB.STRIPE_PAYMENT_EVENTS
  MODIFY COLUMN RESTAURANTGUID VARCHAR(36) FIRST;
ALTER TABLE GRATLYDB.STRIPE_PAYOUT_EVENTS
  MODIFY COLUMN RESTAURANTGUID VARCHAR(36) FIRST;
ALTER TABLE GRATLYDB.STRIPE_RESTAURANT_SETTINGS
  MODIFY COLUMN RESTAURANTGUID VARCHAR(36) FIRST;
ALTER TABLE GRATLYDB.RESTAURANT_PAYMENT_ROUTING
  MODIFY COLUMN RESTAURANTGUID VARCHAR(36) FIRST;
ALTER TABLE GRATLYDB.STRIPE_SETTLEMENT_TRANSFERS
  MODIFY COLUMN RESTAURANTGUID VARCHAR(36) FIRST;
ALTER TABLE GRATLYDB.STRIPE_TRANSFER_EVENTS
  MODIFY COLUMN RESTAURANTGUID VARCHAR(36) FIRST;
